parameters:
- name: ArtifactName
  type: string
  default: 'bins'
- name: Toolchain
  type: string
  default: 'i386-pc-windows-msvc'
- name: Configuration
  type: string
  default: 'Debug'
- name: FunctionalTest
  type: string
  default: 'Build'

jobs:
- job: 'Build'
  displayName: Build
  pool: 
    name: 1pfw-kingsgate-windows
    isCustom: true
    type: windows

  variables:
    ob_outputDirectory: '$(Build.SourcesDirectory)/.build/${{ parameters.Configuration }}/${{ parameters.Toolchain }}/'
    ob_sdl_codeSignValidation_excludes: -|**\*.test*.exe; # Excluding unit tests

  steps: 

    # Set up permissions for other repos
    - template: auth.yaml

    # Main build task, performs setenv for given toolchain/config selected and
    # the build command
    - task: PowerShell@2
      displayName: Build
      env:
        AZURE_DEVOPS_EXT_PAT : $(System.AccessToken)
        ADO_UTIL_TOKEN: $(System.AccessToken)
        ADO_UTIL_ORG: $(System.CollectionUri)
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        targetType: 'inline'
        script: |
          ./start.ps1 -Toolchain ${{ parameters.Toolchain }} -Configuration ${{ parameters.Configuration }}
          build

    - task: PowerShell@2
      displayName: Copy Artifacts
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p publish
          Copy-Item -Path .\.build\${{ parameters.Configuration }}\**\bin\* -Recurse -Destination ./publish
          Copy-Item -Recurse ./publish $(Build.ArtifactStagingDirectory)
          if ('${{ parameters.FunctionalTest }}' -eq "Official") {
              # Copying functional tests to artifacts
              $targetPath = "$(Build.SourcesDirectory)\.build\${{ parameters.Configuration }}\${{ parameters.Toolchain }}\functional_test"
              # Create the target directory if it does not exist
              if (!(Test-Path -Path $targetPath)) {
                  mkdir $targetPath
              }
              # Copy functional tests
              Copy-Item -Path .\tests\* -Recurse -Destination "$targetPath"
          }

    - task: Bash@3
      displayName: Get release notes for Silibs (Bash)
      inputs:
        targetType: 'inline'
        script: |
          pushd .externs/repo/silibs
          mkdir Release_Notes
          git log -100 --pretty --decorate > Release_Notes/Release_Notes_silibs.txt
          pushd libraries/common
          git log -100 --pretty --decorate > ../../Release_Notes/Release_Notes_silibs_common.txt
          popd
          pushd libraries/sdm
          git log -100 --pretty --decorate > ../../Release_Notes/Release_Notes_sdm.txt
          popd
          pushd libraries/crypto
          git log -100 --pretty --decorate > ../../Release_Notes/Release_Notes_crypto.txt
          popd
          popd

    - task: PowerShell@2
      displayName: Get release notes for Silibs (PS)
      inputs:
        targetType: 'inline'
        script: |
          Copy-Item -Path .externs\repo\silibs\Release_Notes -Recurse -Destination $(Build.SourcesDirectory)\.build\${{ parameters.Configuration }}\${{ parameters.Toolchain }}\Release_Notes

    - task: PowerShell@2
      displayName: Publish Platform Config Knobs (PS)
      inputs:
        targetType: 'inline'
        script: |
          $destinationDir = "$(Build.SourcesDirectory)\.build\${{ parameters.Configuration }}\${{ parameters.Toolchain }}\Config_Knobs"
          New-Item -ItemType Directory -Path $destinationDir
          Copy-Item -Path .\.build\${{ parameters.Configuration }}\${{ parameters.Toolchain }}\src\externs\1pfw_fwlibs\include\*.xml -Destination $destinationDir\Kingsgate_MSCP_Platform_Config_Knobs.xml
          Copy-Item -Path .\.build\${{ parameters.Configuration }}\${{ parameters.Toolchain }}\start_of_borgens_range.txt -Destination $destinationDir\SVT_1GB_Reserved_DDR_Start_Address.txt

    - task: PublishSymbols@2
      displayName: Publish Symbol Files - Debug and Release
      condition: succeeded()
      inputs:
        SymbolsFolder: '$(Build.ArtifactStagingDirectory)/publish'
        SearchPattern: |
          *.elf
          *.pdb
        SymbolServerType: 'TeamServices'
        SymbolExpirationInDays: '365'

    # Publish results as a pipeline artifact
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/.build/${{ parameters.Configuration }}/${{ parameters.Toolchain }}/'
        artifact: 'drop_${{ parameters.ArtifactName }}_Build'
        publishLocation: 'pipeline'