#
# Copyright (C) Microsoft Corporation. All rights reserved.
#

parameters:
- name: Toolchain
  type: string
  default: 'arm-eabi-aarch'
- name: Configuration
  type: string
  default: 'Debug' 
- name: ArtifactName
  type: string
  default: 'bins'
- name: Pool
  type: string
  default: '1pfw-kingsgate-bigfpga-pipelines'
- name: TestVehicleCapability
  type: string
  default: 'SingleDieFPGA'  
- name: TestPlan
  type: string
  default: '.\tests\functional\test_plan\fpga_single_die_test_plan.args'
- name: build_id
  type: string
  default: '0'
- name: ifwi
  type: string
  default: 'kingsgate.ifwi.fpga.debug.custom.dat'
- name : TimeoutInMinutes
  type: number
  default: 240

jobs:
- job: 'FPGA_Pythia_Tests'
  timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
  displayName: FPGA Pythia Tests
  pool: 
    name: ${{ parameters.Pool }}
    demands: TestVehicle -equals ${{ parameters.TestVehicleCapability }}
    isCustom: true
    type: windows

  variables:
    ob_outputDirectory: '$(Build.SourcesDirectory)\.testlogs\pythia'
    ob_artifactSuffix: '$(System.JobAttempt)'

  steps: 

    # Set up permissions for other repos
    - template: auth.yaml

    # Dump agent information (useful for debugging)
    - template: agent_info.yaml

    # Download input artifact for CI & nightly run
    - task: DownloadPipelineArtifact@2
      condition: and(succeeded(), eq('${{ parameters.build_id }}', '0'))
      inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop_Build_Arm_EABI_AARCH_Debug_Build'
          downloadPath: '$(Build.SourcesDirectory)\.build\Debug\arm-eabi-aarch'

    # Download input artifact for Nightly and Weekend Stress
    - task: DownloadPipelineArtifact@2
      condition: and(succeeded(), ne('${{ parameters.build_id }}', '0'))
      inputs:
          buildType: 'specific'
          project: '2610da6a-0168-48f8-b34a-f1c882cb6660'  # Woodinville
          definition: '8678'  # Kingsgate.MSCP-Official
          buildVersionToDownload: 'specific'
          buildId: ${{ parameters.build_id}}
          artifactName: 'drop_Build_Arm_EABI_AARCH_Debug_Build'
          downloadPath: '$(Build.SourcesDirectory)\.build\Debug\arm-eabi-aarch'

    # Setup the FPGA
    # TODO: Run OOB Reset
    - task: PowerShell@2
      displayName: 'Pre Test: Prepare FPGA for pipeline'
      env:
        AZURE_DEVOPS_EXT_PAT : $(System.AccessToken)
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        targetType: 'inline'
        showWarnings: true
        script: | 
          # Cleanup pip cache
          pip cache purge

          # Init Env
          ./start.ps1 -Toolchain ${{ parameters.Toolchain }} -Configuration ${{ parameters.Configuration }}
          
          # Kill all Trace32 Sessions
          killt32

          # Kill all Putty Sessions 
          killputty

          # Reset all COM ports
          python .\tests\functional\library\kng_pythia_libs\fpga_reset_com_ports.py

          # Retrieve the agent name
          $agentName = $env:AGENT_NAME
          Write-Host "Agent Name: $agentName"
          $splitAgentName = $agentName -split '-'
          $trimmedAgentName = $splitAgentName[-1]
          Write-Host "Trimmed Agent Name: $trimmedAgentName"
          
          # Kick all users out
          kickuser -pc $trimmedAgentName -user 'all'

          # Flash firmware
          flashscpfw $trimmedAgentName -file ${{ parameters.ifwi }}

          # OOB Reset
          oobreset

          #TODO - Validate on reset ROM FUSE without running as a test
          # Reset FPGA ROM and Fuse Data
          if ($TestVehicle -eq "SingleDieFPGA") {
              Invoke-Pythia .\tests\functional\test_suites\fpga_init\fpga_init_singledie.robot -platform "fpga"
          }
          elseif ($TestVehicle -eq "DualDieFPGA") {
              Invoke-Pythia .\tests\functional\test_suites\fpga_init\fpga_init_dualdie.robot -platform "fpga"
          }


    # 1. Setup the environment
    # 2. Invoke Pythia
    # Logs will be under $(Build.SourcesDirectory)\.testlogs\pythia
    - task: PowerShell@2
      displayName: 'Test: Run FPGA Pythia Tests'
      env:
        AZURE_DEVOPS_EXT_PAT : $(System.AccessToken)
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        targetType: 'inline'
        showWarnings: true
        script: | 
          ./start.ps1 -Toolchain ${{ parameters.Toolchain }} -Configuration ${{ parameters.Configuration }}
          Invoke-Pythia -test ${{ parameters.TestPlan }} -platform fpga

          # Remove intermediate output / output that contains system variables (ie: Azure credentials)
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\output.xml"
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\rlog.txt"
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\generated" -Recurse -Force
          Remove-Item .externs -Force -Recurse

          # Cleanup pip cache after the test
          pip cache purge

    # Publish the results of the test suite
    - task: PublishTestResults@2
      displayName: 'Publish: FPGA Pythia Test Results'
      condition: succeededOrFailed()
      inputs:
        testRunTitle: 'Kingsgate FPGA Pythia Tests'
        testResultsFormat: 'JUnit'
        testResultsFiles: '**\Results.xml'
        searchFolder: '$(Build.SourcesDirectory)\.testlogs\pythia'
        failTaskOnFailedTests: true
        publishRunAttachments: true
        mergeTestResults: true

    # Publish results as a pipeline artifact
    - task: PublishPipelineArtifact@1
      displayName: 'Publish: Pipeline Artifacts'
      condition: succeededOrFailed()
      inputs:
        targetPath: $(Build.SourcesDirectory)\.testlogs\pythia
        artifact: 'drop_${{ parameters.ArtifactName }}_FPGA_Pythia_Tests$(System.JobAttempt)'
        publishLocation: 'pipeline'
        parallel: true
