#
# Copyright (C) Microsoft Corporation. All rights reserved.
#

parameters:
- name: Toolchain
  type: string
  default: 'arm-eabi-aarch'
- name: Configuration
  type: string
  default: 'Debug' 
- name: ArtifactName
  type: string
  default: 'bins'
- name: Pool
  type: string
  default: '1pfw-kingsgate-big-fpga'  
- name: TestAgent
  type: string
  default: 'DH3'
- name: TestPlan
  type: string
  default: '.\tests\functional\pythia\test_plan\fpga_single_die_test_plan.args'
- name: build_id
  type: string
  default: '0'
- name: dat_file
  type: string
  default: 'kingsgate.ifwi.fpga.debug.custom.dat'


jobs:
- job: 'FPGA_Pythia_Tests'
  timeoutInMinutes: 240
  displayName: FPGA Pythia Tests
  pool: 
    name: ${{ parameters.Pool }}
    demands: Agent.Name -equals RDU-120015-${{ parameters.TestAgent }}
    isCustom: true
    type: windows

  variables:
    ob_outputDirectory: '$(Build.SourcesDirectory)\.testlogs\pythia'
    ob_artifactSuffix: '$(System.JobAttempt)'

  steps: 

    # Set up permissions for other repos
    - template: auth.yaml

    # Dump agent information (useful for debugging)
    - template: agent_info.yaml

    # Download input artifact for CI & nightly run
    - task: DownloadPipelineArtifact@2
      condition: and(succeeded(), eq('${{ parameters.build_id }}', '0'))
      inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop_Build_Arm_EABI_AARCH_Debug_Build'
          downloadPath: '$(System.ArtifactsDirectory)/bins.arm-eabi-aarch.Debug'

    # Download input artifact for Nightly and Weekend Stress
    - task: DownloadPipelineArtifact@2
      condition: and(succeeded(), ne('${{ parameters.build_id }}', '0'))
      inputs:
          buildType: 'specific'
          project: '2610da6a-0168-48f8-b34a-f1c882cb6660'  # Woodinville
          definition: '5440'  # kingsgate.mscp.ci
          buildVersionToDownload: 'specific'
          buildId: ${{ parameters.build_id}}
          artifactName: 'drop_Build_Arm_EABI_AARCH_Debug_Build'
          downloadPath: '$(System.ArtifactsDirectory)/bins.arm-eabi-aarch.Debug'
 
    # Setup the FPGA
    # TODO: Run OOB Reset
    - task: PowerShell@2
      displayName: 'Pre Test: Prepare FPGA for pipeline'
      env:
        AZURE_DEVOPS_EXT_PAT : $(System.AccessToken)
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        targetType: 'inline'
        showWarnings: true
        script: | 

          # Cleanup pip cache
          pip cache purge

          # Init Env
          ./start.ps1 -Toolchain ${{ parameters.Toolchain }} -Configuration ${{ parameters.Configuration }}
          
          # Kill all Trace32 Sessions
          killt32

          # Kill all Putty Sessions 
          killputty

          # Reset all COM ports
          python .\tests\functional\pythia\pylibs\kng_pythia_libs\fpga_reset_com_ports.py
          
          # Kick all users out
          kickuser -pc ${{ parameters.TestAgent }} -user 'all'

          # Flash Firmware
          flashscpfw ${{ parameters.TestAgent }} -file ${{ parameters.dat_file }}

          # Reset FPGA ROM and Fuse Data
          Invoke-Pythia -test .\tests\functional\pythia\test_suites\fpga_init\fpga_init.robot -platform fpga

 
    # 1. Setup the environment
    # 2. Build the FW
    # 3. Invoke Pythia
    # Logs will be under $(Build.SourcesDirectory)\.testlogs\pythia
    - task: PowerShell@2
      displayName: Run Test Suites
      env:
        AZURE_DEVOPS_EXT_PAT : $(System.AccessToken)
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        targetType: 'inline'
        showWarnings: true
        script: | 
          ./start.ps1 -Toolchain ${{ parameters.Toolchain }} -Configuration ${{ parameters.Configuration }}
          $bin_src_dir = "$(System.ArtifactsDirectory)/bins.arm-eabi-aarch.Debug/bin"
          $bin_dest_dir = "${env:REPO_APP_BUILD_DIR}/${env:REPO_APP_BUILD_CONFIG}/arm-eabi-aarch"
          Copy-Item $bin_src_dir $bin_dest_dir -Recurse -Force
          
          Invoke-Pythia -test ${{ parameters.TestPlan }} -platform fpga

        # Remove intermediate output / output that contains system variables (ie: Azure credentials)
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\output.xml"
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\rlog.txt"
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\generated" -Recurse -Force
          Remove-Item .externs -Force -Recurse

        # Cleanup pip cache
          pip cache purge

    # Publish the results of the test suite
    - task: PublishTestResults@2
      displayName: Publish FPGA Pythia Tests Results
      condition: succeededOrFailed()
      inputs:
        testRunTitle: 'Kingsgate FPGA Pythia Tests'
        testResultsFormat: 'JUnit'
        testResultsFiles: '**\Results.xml'
        searchFolder: '$(Build.SourcesDirectory)\.testlogs\pythia'
        failTaskOnFailedTests: true
        publishRunAttachments: true
        mergeTestResults: true

    # Publish results as a pipeline artifact
    - task: PublishPipelineArtifact@1
      condition: succeededOrFailed()
      inputs:
        targetPath: '$(Build.SourcesDirectory)\.testlogs\pythia'
        artifact: 'drop_${{ parameters.ArtifactName }}_FPGA_Pythia_Tests$(System.JobAttempt)'
        publishLocation: 'pipeline'
        parallel: true
