parameters:
- name: ArtifactName
  type: string
  default: 'kingsgate_mscp'

jobs:
- job: 'Tag'
  displayName: Tag
  pool:
    name: 1pfw-kingsgate-windows
    demands:
    - ImageOverride -equals 1pfw-win2022vNext
    isCustom: true
    type: windows
  steps: 
    - checkout: self
      persistCredentials: true

    # Set up permissions for other repos
    - template: auth.yaml

    # git tag task. Creates an incremental tag based on every PR completion
    - task: PowerShell@2
      displayName: gitTag
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        targetType: 'inline'
        script: |
          git tag '${{ parameters.ArtifactName }}_v$(Build.BuildNumber)'
          git push origin '${{ parameters.ArtifactName }}_v$(Build.BuildNumber)'
