parameters:
- name: Toolchain
  type: string
  default: 'arm-eabi-aarch'
- name: Configuration
  type: string
  default: 'Debug'
- name: ArtifactName
  type: string
  default: 'bins'
- name: Pool
  type: string
  default: '1pfw-kingsgate-windows'   
- name: stress_test_iterations
  default: "1"
- name: build_id
  type: string
  default: ''
- name: TestFolder
  type: string
  default: '.\tests\functional\pythia\test_suites\svp_fpga_single_die\'

jobs:
- job: 'SVP_Pythia_Tests'
  timeoutInMinutes: 240
  displayName: SVP Pythia Tests
  pool: 
    name: ${{ parameters.Pool }}
    isCustom: true
    type: windows

  variables:
    ob_outputDirectory: '$(Build.SourcesDirectory)\.testlogs\pythia'

  steps: 

    # Set up permissions for other repos
    - template: auth.yaml

    # Dump agent information (useful for debugging)
    - template: agent_info.yaml

    #print the count
    - script: |
       echo "stress_test_iterations count ${{ parameters.stress_test_iterations }}"
       echo "stress_test_iterations count (var) $(stress_test_iterations)"
      displayName: "Print stress_test_iterations value "

    # Download input artifact for CI & nightly run
    - task: DownloadPipelineArtifact@2
      condition: and(succeeded(), eq('${{ parameters.stress_test_iterations }}', '1'))
      inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop_Build_Arm_EABI_AARCH_Debug_Build'
          downloadPath: '$(System.ArtifactsDirectory)/bins.arm-eabi-aarch.Debug'

    # Download input artifact for nightlystress and weekendstress
    - task: DownloadPipelineArtifact@2
      condition: and(succeeded(), ne('${{ parameters.stress_test_iterations }}', '1'))
      inputs:
          buildType: 'specific'
          project: '2610da6a-0168-48f8-b34a-f1c882cb6660'  # Woodinville
          definition: '5440'  # kingsgate.mscp.ci
          buildVersionToDownload: 'specific'
          buildId: ${{ parameters.build_id}}
          artifactName: 'drop_Build_Arm_EABI_AARCH_Debug_Build'
          downloadPath: '$(System.ArtifactsDirectory)/bins.arm-eabi-aarch.Debug'

    # 1. Setup the environment
    # 2. Build the FW
    # 3. Invoke Pythia
    # Logs will be under $(Build.SourcesDirectory)\.testlogs\pythia
    - task: PowerShell@2
      displayName: Run Test Suites
      env:
        AZURE_DEVOPS_EXT_PAT : $(System.AccessToken)
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        #stress_test_iterations: $(stress_test_iterations)
        targetType: 'inline'
        showWarnings: true
        script: | 
          ./start.ps1 -Toolchain ${{ parameters.Toolchain }} -Configuration ${{ parameters.Configuration }}

          $bin_src_dir = "$(System.ArtifactsDirectory)/bins.arm-eabi-aarch.Debug/bin"
          $bin_dest_dir = "${env:REPO_APP_BUILD_DIR}/${env:REPO_APP_BUILD_CONFIG}/arm-eabi-aarch"
          Copy-Item $bin_src_dir $bin_dest_dir -Recurse -Force

          $stressTestIterations = ${{ parameters.stress_test_iterations}}

          if ($stressTestIterations -gt 1) {
              Invoke-Pythia-Stress -test ${{ parameters.TestFolder }} -platform svp -stress_iteration ${{ parameters.stress_test_iterations }}
          } else {
              $artifactName = "${{ parameters.ArtifactName }}"
              switch ($artifactName) { #To make sure all other pipelines run as designed till TestFolder is implemented across all.
                  "SVP_Pythia_Tests" {
                      Invoke-Pythia -test .\tests\functional\pythia\test_suites\svp_fpga_single_die\ -platform svp
                      Invoke-Pythia -test .\tests\functional\pythia\test_suites\fpga_only_single_die\ -platform svp
                  }
                  default {
                      Invoke-Pythia -test ${{ parameters.TestFolder }} -platform svp
                  }
              }
          }


          # Remove intermediate output / output that contains system variables (ie: Azure credentials)
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\output.xml"
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\rlog.txt"
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\generated" -Recurse -Force
          Remove-Item .externs -Force -Recurse

    # Publish the results of the test suite
    - task: PublishTestResults@2
      displayName: Publish SVP Pythia Tests Results
      condition: succeededOrFailed()
      inputs:
        testRunTitle: 'Kingsgate SVP Pythia Tests'
        testResultsFormat: 'JUnit'
        testResultsFiles: '**\Results.xml'
        searchFolder: '$(Build.SourcesDirectory)\.testlogs\pythia'
        failTaskOnFailedTests: true
        publishRunAttachments: true
        mergeTestResults: true

    # Publish results as a pipeline artifact
    - task: PublishPipelineArtifact@1
      condition: succeededOrFailed()
      inputs:
        targetPath: '$(Build.SourcesDirectory)\.testlogs\pythia'
        artifact: 'drop_${{ parameters.ArtifactName }}_SVP_Pythia_Tests'
        publishLocation: 'pipeline'
        parallel: true
