parameters:
- name: Toolchain
  type: string
  default: 'arm-eabi-aarch'
- name: Configuration
  type: string
  default: 'Debug'
- name: ArtifactName
  type: string
  default: 'bins'
- name: Pool
  type: string
  default: '1pfw-kingsgate-windows'
- name: TestPlan
  type: string
  default: '.\tests\functional\pythia\test_plan\svp_single_die_ci_test_plan.args'
- name: build_id
  type: string
  default: '0'
- name : ifwi
  type: string
  default: 'kingsgate.ifwi.svp.debug.custom.dat'

jobs:
- job: 'SVP_Pythia_Tests'
  timeoutInMinutes: 240
  displayName: SVP Pythia Tests
  pool: 
    name: ${{ parameters.Pool }}
    isCustom: true
    type: windows

  variables:
    ob_outputDirectory: '$(Build.SourcesDirectory)\.testlogs\pythia'
    ob_artifactSuffix: '$(System.JobAttempt)'

  steps: 

    # Set up permissions for other repos
    - template: auth.yaml

    # Dump agent information (useful for debugging)
    - template: agent_info.yaml

    # Download input artifact for CI & nightly run
    - task: DownloadPipelineArtifact@2
      condition: and(succeeded(), eq('${{ parameters.build_id }}', '0'))
      inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop_Build_Arm_EABI_AARCH_Debug_Build'
          downloadPath: '$(Build.SourcesDirectory)\.build\Debug\arm-eabi-aarch'

    # Download input artifact for nightlystress and weekendstress
    - task: DownloadPipelineArtifact@2
      condition: and(succeeded(), ne('${{ parameters.build_id }}', '0'))
      inputs:
          buildType: 'specific'
          project: '2610da6a-0168-48f8-b34a-f1c882cb6660'  # Woodinville
          definition: '8678'  # Kingsgate.MSCP-Official
          buildVersionToDownload: 'specific'
          buildId: ${{ parameters.build_id}}
          artifactName: 'drop_Build_Arm_EABI_AARCH_Debug_Build'
          downloadPath: '$(Build.SourcesDirectory)\.build\Debug\arm-eabi-aarch'

    # 1. Setup the environment
    # 2. Invoke Pythia
    # Logs will be stored under $(Build.SourcesDirectory)\.testlogs\pythia
    - task: PowerShell@2
      displayName: Run Test Suites
      env:
        AZURE_DEVOPS_EXT_PAT : $(System.AccessToken)
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        targetType: 'inline'
        showWarnings: true
        script: | 
          ./start.ps1 -Toolchain ${{ parameters.Toolchain }} -Configuration ${{ parameters.Configuration }}

          # Run the test suite
          Invoke-Pythia -test ${{ parameters.TestPlan }} -platform svp -ifwi ${{ parameters.ifwi }}

          # Remove intermediate output / output that contains system variables (ie: Azure credentials)
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\output.xml"
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\rlog.txt"
          Remove-Item "$(Build.SourcesDirectory)\.testlogs\pythia\**\generated" -Recurse -Force
          Remove-Item .externs -Force -Recurse

    # Publish the results of the test suite
    - task: PublishTestResults@2
      displayName: 'Publish: SVP Pythia Test Results'
      condition: succeededOrFailed()
      inputs:
        testRunTitle: 'Kingsgate SVP Pythia Tests'
        testResultsFormat: 'JUnit'
        testResultsFiles: '**\Results.xml'
        searchFolder: '$(Build.SourcesDirectory)\.testlogs\pythia'
        failTaskOnFailedTests: false
        publishRunAttachments: true
        mergeTestResults: true

    # Publish results as a pipeline artifact
    - task: PublishPipelineArtifact@1
      displayName: 'Publish: Pipeline Artifacts'
      condition: succeededOrFailed()
      inputs:
        targetPath: '$(Build.SourcesDirectory)\.testlogs\pythia'
        artifact: 'drop_${{ parameters.ArtifactName }}_SVP_Pythia_Tests$(System.JobAttempt)'
        publishLocation: 'pipeline'
        parallel: true
