parameters:
- name: Toolchain
  type: string
  default: 'i386-pc-windows-msvc'
- name: Configuration
  type: string
  default: 'Debug'
- name: BranchCoverage
  type: string
  default: '0.0'
- name: LineCoverage
  type: string
  default: '0.0'
- name: ArtifactName
  type: string
  default: 'bins'

jobs:
- job: 'Unit_Tests'
  displayName: Unit Tests
  pool: 
    name: 1pfw-kingsgate-windows
    demands: 
      - ImageOverride -equals 1pfw-win2022vNext
      - ImageVersionOverride -equals 144.0.0
    isCustom: true
    type: windows
  steps: 

    # Set up permissions for other repos
    - template: auth.yaml

    - task: UseDotNet@2
      continueOnError: true
      inputs:
        packageType: 'sdk'
        version: 6.x
        performMultiLevelLookup: true

    # Main test task, loads test scripts and runs the orchestrator
    - task: PowerShell@2
      displayName: Build and Unit Tests
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        targetType: 'inline'
        script: |
          $env:AZURE_DEVOPS_EXT_PAT = "$(System.AccessToken)"
          $env:REPO_APP_ROOT = "$(Build.SourcesDirectory)"

          ./start.ps1 -Toolchain ${{ parameters.Toolchain }} -Configuration ${{ parameters.Configuration }}
          build
          
          $TargetLogDir = "$(System.ArtifactsDirectory)\Unit_Test_Logs"
          & "${env:REPO_APP_PATH_1pfw.tools.win64}\sptest" `
            /devicesfile:"$(Build.SourcesDirectory)\tests\unit\SpTestDevices.xml" `
            /packagesdir:"$(Build.SourcesDirectory)\.build\${{ parameters.Configuration }}\${{ parameters.Toolchain }}"\bin `
            /logsdir:"$TargetLogDir" `
            /define:test_bin_dir="$(Build.SourcesDirectory)\.build\${{ parameters.Configuration }}\${{ parameters.Toolchain }}"\bin `
            /define:test_src_dir="$(Build.SourcesDirectory)" `
            /runtests

          $GcovrCoverageDir = (Get-ChildItem $TargetLogDir | Sort -Descending)[0].FullName
          $GcovrCoverageDir = "$GcovrCoverageDir/gcov_reports/"
          mkdir "$GcovrCoverageDir" -Force
          $GcovOutput = $GcovrCoverageDir.replace("\", "/")
          $RepoRoot = $env:REPO_APP_ROOT.replace("\", "/")
          $GcovRoot = "$(System.ArtifactsDirectory)/bins.arm-eabi-aarch.Debug".replace("\", "/")
          & gcovr --root $RepoRoot --object-directory "$GcovRoot" --filter "${RepoRoot}src/" --gcov-ignore-errors=no_working_dir_found --verbose `
                  --exclude-unreachable-branches --gcov-executable "${env:REPO_APP_PATH_gcc.arm.eabi.aarch-win64}/bin/arm-none-eabi-gcov.exe" `
                  --exclude ".+_cli.c" --exclude ".+cli_power.c" --exclude ".+cli_ddr.c" --cobertura --output $GcovOutput

          & "${env:REPO_APP_PATH_report-generator}/tools/net6.0/ReportGenerator.exe" `
            -reports:"$(System.ArtifactsDirectory)\Unit_Test_Logs\**\**\cobertura.xml" `
            -targetdir:"$(System.ArtifactsDirectory)\Coverage" `
            -sourcedirs:"$(Build.SourcesDirectory)\src" `
            -reporttypes:"Cobertura"

    - task: PublishTestResults@2
      displayName: Publish Unit Tests Results
      condition: succeededOrFailed()
      inputs:
        testRunTitle: '[Windows] Kingsgate Unit Tests'
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/TestRun_*.trx'
        searchFolder: '$(System.ArtifactsDirectory)\Unit_Test_Logs'
        failTaskOnFailedTests: true
        publishRunAttachments: true

    # code coverage
    # when unittest is invoked locally, the summary file can be found in:
    #   .\.testlogs\<TestRun_#>\Coverage\Cobertura.xml
    # the summary file exposes branch and line coverage rates which are checked against a target
    # the target coverages are provided to this template as parameters and are clipped between 0.0 and 1.0
    - task: PublishCodeCoverageResults@2
      displayName: Publish Code Coverage
      condition: succeededOrFailed()
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(System.ArtifactsDirectory)\Coverage\Cobertura.xml'
        pathToSources: '$(Build.SourcesDirectory)\'

    # check code coverage against target    
    - task: Powershell@2
      displayName: Check Coverage
      inputs:
        targetType: 'inline'
        script: |
          # get xml object
          $cov_xml = [xml] (get-content -raw "$(System.ArtifactsDirectory)\Coverage\Cobertura.xml")

          # type-check and convert coverage parameters to numbers
          $lineCoverage = 0.0
          $branchCoverage = 0.0
          if (${{ parameters.LineCoverage }} -is [int] -or ${{ parameters.LineCoverage }} -is [double]) {
            $lineCoverage = [Math]::Max(0.0, [Math]::Min(1.0, ${{ parameters.LineCoverage }} ))
          } else {
            Write-Host "LineCoverage parameter is not a number! Using 0.0 coverage target."
          }
          if (${{ parameters.BranchCoverage }} -is [int] -or ${{ parameters.BranchCoverage }} -is [double]) {
            $branchCoverage = [Math]::Max(0.0, [Math]::Min(1.0, ${{ parameters.BranchCoverage }} ))
          } else {
            Write-Host "BranchCoverage parameter is not a number! Using 0.0 coverage target."
          }

          # check coverage rates
          Write-Host  "Line coverage:   Target [" $lineCoverage "] Actual [" $cov_xml.coverage.'line-rate' "]"
          Write-Host  "Branch coverage: Target [" $branchCoverage "] Actual [" $cov_xml.coverage.'branch-rate' "]"
          if ($cov_xml.coverage.'line-rate' -lt $lineCoverage) {
            throw "Line coverage is less than target!"
          }
          if ($cov_xml.coverage.'branch-rate' -lt $branchCoverage) {
            throw "Branch coverage is less than target!"
          }
          Write-Host "Coverage check passed!"
