//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

/**
 * @file atu_api.h
 * Header containing definitions for the atu module driver interface.
 */

#pragma once

/*----------- Nested includes ------------*/
#include <DfwkDriver.h>
#include <DfwkTypes.h>
#include <DfwkCommon.h>
#include <assert.h>
#include <kng_soc_constants.h>
#include <memory_map/ddrss_reserved_regions.h>
#include <silibs_ap_top_regs.h>
#include <silibs_scp_top_regs.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <vab_cded_ioss_top_regs.h>

/*-- Symbolic Constant Macros (defines) --*/

#define IS_ALIGNED(addr, size) (((uintptr_t)(addr) & ((size) - 1)) == 0)

/**
 * 1. All addresses, including the addresses in the AP Space, must be aligned to the ATU page size.
 *
 * 2. All base and end addresses are inclusive, meaning the end address is the last address accessible
 *    addresses in the range. For example, if the base address is 0x1000 and the size is 0x1000, the
 *    end address is 0x1FFF.
 *
 * 3. The mapped addresses in AP Window for the MSCP are back to back. Meaning that the next window
 *    starts at the next ATU Page aligned address after the end address of the previous window.
 *
 * 4. The below mappings into the AP Window are the final static mappings applied for the MSCP. Any
 *    mappings initialized before the ATU Service will be overridden by these mappings, therefore any
 *    runtime dependencies on ATU mappings should depend on the ATU Service, and utilize these maps.
 * 
 * 5. For mappings that need MPU regions applied remember, the AP Window is a 2 GB window, starting at 
 *    an address that is not 2 GB Aligned. MPU Regions need start addresses to be aligned to the region
 *    size. Therefore, any region here that needs a MPU region must align it's start address within this
 *    window to the MPU region size. This can result in gaps in the overall window. 
 */

// The SCP and MCP have the same start address for the AP Window, so we can use the SCP's address
#define MSCP_ATU_AP_WINDOW_SIZE (SCP_TOP_ATU_AP_WINDOW_MEM_SIZE)
#define MSCP_ATU_AP_WINDOW_BASE_ADDRESS (SCP_TOP_ATU_AP_WINDOW_MEM_ADDRESS)
#define MSCP_ATU_AP_WINDOW_END_ADDRESS (MSCP_ATU_AP_WINDOW_BASE_ADDRESS + MSCP_ATU_AP_WINDOW_SIZE)

// We map the ARSM on both DIEs into the window
#define MSCP_ATU_AP_WINDOW_ARSM_DIE_0_SIZE (AP_TOP_D0_ARSM_SHARED_SRAM_SIZE)
#define MSCP_ATU_AP_WINDOW_ARSM_DIE_0_BASE_ADDR (MSCP_ATU_AP_WINDOW_BASE_ADDRESS)
#define MSCP_ATU_AP_WINDOW_ARSM_DIE_0_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_ARSM_DIE_0_BASE_ADDR + MSCP_ATU_AP_WINDOW_ARSM_DIE_0_SIZE, ATU_PAGE_SIZE) - 1

#define MSCP_ATU_AP_WINDOW_ARSM_DIE_1_SIZE (AP_TOP_D1_ARSM_SHARED_SRAM_SIZE)
#define MSCP_ATU_AP_WINDOW_ARSM_DIE_1_BASE_ADDR (MSCP_ATU_AP_WINDOW_ARSM_DIE_0_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_ARSM_DIE_1_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_ARSM_DIE_1_BASE_ADDR + MSCP_ATU_AP_WINDOW_ARSM_DIE_1_SIZE, ATU_PAGE_SIZE) - 1

// We only need to map the core cluster on the die into the window, and the cluster size is the same on each die
#define MSCP_ATU_AP_WINDOW_CORE_CLUSTER_DIE_SIZE (AP_TOP_D0_CORE_CLUSTER_SIZE)
#define MSCP_ATU_AP_WINDOW_CORE_CLUSTER_DIE_BASE_ADDR (MSCP_ATU_AP_WINDOW_ARSM_DIE_1_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_CORE_CLUSTER_DIE_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_CORE_CLUSTER_DIE_BASE_ADDR + MSCP_ATU_AP_WINDOW_CORE_CLUSTER_DIE_SIZE, ATU_PAGE_SIZE) - 1

// Each die has a unique DDR range for IB Telemetry, but window location is the same for both dies
// the inband telemetry reserved memory is evenly split between the two dies
#define MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_SIZE ((IB_TELEMETRY_RESERVATION_END - IB_TELEMETRY_RESERVATION_BASE) / 2)
#define MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_BASE_ADDR ALIGN_UP((MSCP_ATU_AP_WINDOW_CORE_CLUSTER_DIE_END_ADDR + 1), MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_SIZE)
#define MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_BASE_ADDR + MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_SIZE, ATU_PAGE_SIZE) - 1
static_assert(IS_ALIGNED(MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_BASE_ADDR, 128*SL_1MB), "MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_BASE_ADDR not aligned to 128 MB! Required for MPU!");

// Due to resource constraints some of the payloads for ICC via MHU reside within DDR. We map the
// entire range (even the other dies payload regions).
#define MSCP_ATU_AP_WINDOW_ICC_MHU_PAYLOAD_SIZE (ICC_MHU_PAYLOADS_RESERVATION_END - ICC_MHU_PAYLOADS_RESERVATION_BASE)
#define MSCP_ATU_AP_WINDOW_ICC_MHU_PAYLOAD_BASE_ADDR ALIGN_UP((MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_END_ADDR + 1), MSCP_ATU_AP_WINDOW_ICC_MHU_PAYLOAD_SIZE)
#define MSCP_ATU_AP_WINDOW_ICC_MHU_PAYLOAD_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_ICC_MHU_PAYLOAD_BASE_ADDR + MSCP_ATU_AP_WINDOW_ICC_MHU_PAYLOAD_SIZE, ATU_PAGE_SIZE) - 1
static_assert(IS_ALIGNED(MSCP_ATU_AP_WINDOW_ICC_MHU_PAYLOAD_BASE_ADDR, 16*SL_1KB), "MSCP_ATU_AP_WINDOW_ICC_MHU_PAYLOAD_BASE_ADDR not aligned to 16 KB! Required for MPU!");

// Variable Service DDR region
#define MSCP_ATU_AP_WINDOW_VAR_SVC_DIE_SIZE ((MSCP_VAR_SVC_PAYLOADS_RESERVATION_END - MSCP_VAR_SVC_PAYLOADS_RESERVATION_BASE) / 2)
#define MSCP_ATU_AP_WINDOW_VAR_SVC_BASE_ADDR (MSCP_ATU_AP_WINDOW_ICC_MHU_PAYLOAD_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_VAR_SVC_TEST_PAYLOAD_BASE (MSCP_ATU_AP_WINDOW_VAR_SVC_BASE_ADDR)
#define MSCP_ATU_AP_WINDOW_VAR_SVC_TEST_PAYLOAD_BASE_SIZE (SL_1KB)
#define MSCP_ATU_AP_WINDOW_VAR_SVC_PCIE_PAYLOAD_BASE (MSCP_ATU_AP_WINDOW_VAR_SVC_TEST_PAYLOAD_BASE + MSCP_ATU_AP_WINDOW_VAR_SVC_TEST_PAYLOAD_BASE_SIZE)
#define MSCP_ATU_AP_WINDOW_VAR_SVC_PCIE_PAYLOAD_SIZE (2*SL_1KB)
#define MSCP_ATU_AP_WINDOW_VAR_SVC_PPR_PAYLOAD_BASE (MSCP_ATU_AP_WINDOW_VAR_SVC_PCIE_PAYLOAD_BASE + MSCP_ATU_AP_WINDOW_VAR_SVC_PCIE_PAYLOAD_SIZE)
#define MSCP_ATU_AP_WINDOW_VAR_SVC_PPR_PAYLOAD_SIZE (SL_1KB)
#define MSCP_ATU_AP_WINDOW_VAR_SVC_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_VAR_SVC_BASE_ADDR + MSCP_ATU_AP_WINDOW_VAR_SVC_DIE_SIZE, ATU_PAGE_SIZE) - 1

static_assert((uint64_t)(MSCP_ATU_AP_WINDOW_VAR_SVC_PPR_PAYLOAD_BASE + MSCP_ATU_AP_WINDOW_VAR_SVC_PPR_PAYLOAD_SIZE) < (uint64_t)(MSCP_ATU_AP_WINDOW_VAR_SVC_END_ADDR), "Variable service payloads do not fit in the region!");

// Crash dump DDR region
#define MSCP_ATU_AP_WINDOW_CRASH_DUMP_HEADER_SIZE (8 * SL_1KB)
#define MSCP_ATU_AP_WINDOW_CRASH_DUMP_HEADER_BASE_ADDR (MSCP_ATU_AP_WINDOW_VAR_SVC_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_CRASH_DUMP_HEADER_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_CRASH_DUMP_HEADER_BASE_ADDR + MSCP_ATU_AP_WINDOW_CRASH_DUMP_HEADER_SIZE, ATU_PAGE_SIZE) - 1

#define MSCP_ATU_AP_WINDOW_CRASH_DUMP_DIE_SIZE ((CRASH_DUMP_RESERVATION_END - CRASH_DUMP_RESERVATION_BASE - MSCP_ATU_AP_WINDOW_CRASH_DUMP_HEADER_SIZE) / 2) // 4MB for each die
#define MSCP_ATU_AP_WINDOW_CRASH_DUMP_BASE_ADDR (MSCP_ATU_AP_WINDOW_CRASH_DUMP_HEADER_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_CRASH_DUMP_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_CRASH_DUMP_BASE_ADDR + MSCP_ATU_AP_WINDOW_CRASH_DUMP_DIE_SIZE, ATU_PAGE_SIZE) - 1

// The MSCP Die 0 <-> MSCP Die 1 Send Frame MHU IP Blocks are in the AP Address Space. Map those here.
#define MSCP_ATU_AP_WINDOW_ICC_MHU_SCP2SCP_SEND_FRAME_SIZE (AP_TOP_D0_SCP1R2SCP_MHU_SND_NS_SIZE)
#define MSCP_ATU_AP_WINDOW_ICC_MHU_SCP2SCP_SEND_FRAME_BASE_ADDR (MSCP_ATU_AP_WINDOW_CRASH_DUMP_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_ICC_MHU_SCP2SCP_SEND_FRAME_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_ICC_MHU_SCP2SCP_SEND_FRAME_BASE_ADDR + MSCP_ATU_AP_WINDOW_ICC_MHU_SCP2SCP_SEND_FRAME_SIZE, ATU_PAGE_SIZE) - 1

#define MSCP_ATU_AP_WINDOW_ICC_MHU_MCP2MCP_SEND_FRAME_SIZE (AP_TOP_D0_MCP3R2MCP_MHU_SND_NS_SIZE)
#define MSCP_ATU_AP_WINDOW_ICC_MHU_MCP2MCP_SEND_FRAME_BASE_ADDR (MSCP_ATU_AP_WINDOW_ICC_MHU_SCP2SCP_SEND_FRAME_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_ICC_MHU_MCP2MCP_SEND_FRAME_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_ICC_MHU_MCP2MCP_SEND_FRAME_BASE_ADDR + MSCP_ATU_AP_WINDOW_ICC_MHU_MCP2MCP_SEND_FRAME_SIZE, ATU_PAGE_SIZE) - 1

// Single DIE or DIE0 IOSS Semaphore region
#define MSCP_ATU_AP_WINDOW_IOSS_SIZE (VAB_CDED_IOSS_TOP_IOSS_SIZE + VAB_CDED_IOSS_TOP_UNUSED1_SIZE + VAB_CDED_IOSS_TOP_AFM_SW_SIZE)
#define MSCP_ATU_AP_WINDOW_IOSS_D0_BASE_ADDR (MSCP_ATU_AP_WINDOW_ICC_MHU_MCP2MCP_SEND_FRAME_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_IOSS_D0_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_IOSS_D0_BASE_ADDR + MSCP_ATU_AP_WINDOW_IOSS_SIZE, ATU_PAGE_SIZE) - 1

// DIE1 IOSS semaphore region
#define MSCP_ATU_AP_WINDOW_IOSS_D1_BASE_ADDR (MSCP_ATU_AP_WINDOW_IOSS_D0_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_IOSS_D1_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_IOSS_D1_BASE_ADDR + MSCP_ATU_AP_WINDOW_IOSS_SIZE, ATU_PAGE_SIZE) - 1

// PCIe CHBCR DDR Region
#define MSCP_ATU_AP_WINDOW_CHBCR_SIZE ((CHBCR_RESERVATION_END - CHBCR_RESERVATION_BASE))
#define MSCP_ATU_AP_WINDOW_CHBCR_BASE_ADDR (MSCP_ATU_AP_WINDOW_IOSS_D1_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_CHBCR_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_CHBCR_BASE_ADDR + MSCP_ATU_AP_WINDOW_CHBCR_SIZE, ATU_PAGE_SIZE) - 1

// D0_GIC - GICD space for RAS/CPER notification
#define MSCP_ATU_AP_WINDOW_GIC_GICD_SIZE (AP_TOP_D0_GIC_SIZE)
#define MSCP_ATU_AP_WINDOW_GIC_GICD_BASE_ADDR (MSCP_ATU_AP_WINDOW_CHBCR_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_GIC_GICD_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_GIC_GICD_BASE_ADDR + MSCP_ATU_AP_WINDOW_GIC_GICD_SIZE, ATU_PAGE_SIZE) - 1

// D0_AP_UART_NS - UART space for MCP access
#define MSCP_ATU_AP_WINDOW_UART_NS_SIZE (AP_TOP_D0_AP_UART_NS_SIZE)
#define MSCP_ATU_AP_WINDOW_UART_NS_BASE_ADDR (MSCP_ATU_AP_WINDOW_GIC_GICD_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_UART_NS_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_UART_NS_BASE_ADDR + MSCP_ATU_AP_WINDOW_UART_NS_SIZE, ATU_PAGE_SIZE) - 1

//Cstate timestamps region
#define MSCP_ATU_AP_WINDOW_CSTATE_TIMESTAMP_DIE_SIZE (8 * SL_1KB)
#define MSCP_ATU_AP_WINDOW_CSTATE_TIMESTAMP_DIE_BASE_ADDR (MSCP_ATU_AP_WINDOW_UART_NS_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_CSTATE_TIMESTAMP_DIE_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_CSTATE_TIMESTAMP_DIE_BASE_ADDR + MSCP_ATU_AP_WINDOW_CSTATE_TIMESTAMP_DIE_SIZE, ATU_PAGE_SIZE) - 1

// Advlogger compress buffer
#define MSCP_ATU_AP_WINDOW_ADVLOG_COMPRESS_BUFFER_SIZE (AP_ADV_LOGGER_COMPRESS_BUFFER_SIZE)
#define MSCP_ATU_AP_WINDOW_ADVLOG_COMPRESS_BUFFER_BASE_ADDR (MSCP_ATU_AP_WINDOW_CSTATE_TIMESTAMP_DIE_END_ADDR + 1)
#define MSCP_ATU_AP_WINDOW_ADVLOG_COMPRESS_BUFFER_END_ADDR ALIGN_UP(MSCP_ATU_AP_WINDOW_ADVLOG_COMPRESS_BUFFER_BASE_ADDR + MSCP_ATU_AP_WINDOW_ADVLOG_COMPRESS_BUFFER_SIZE, ATU_PAGE_SIZE) - 1

// total inband telemetry DDR size is split evenly between the two dies and the AP window is sized the same
#define IB_TELEMETRY_DDR_PER_DIE_SIZE       (MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_SIZE)
#define IB_TELEMETRY_DDR_TOTAL_AP_BASE_ADDR (IB_TELEMETRY_RESERVATION_BASE)
#define IB_TELEMETRY_DDR_TOTAL_AP_END_ADDR  (IB_TELEMETRY_RESERVATION_END)
#define IB_TELEMETRY_DDR_TOTAL_SIZE         (IB_TELEMETRY_DDR_TOTAL_AP_END_ADDR - IB_TELEMETRY_DDR_TOTAL_AP_BASE_ADDR)

#define IB_TELEMETRY_DDR_DIE_0_AP_BASE_ADDR (IB_TELEMETRY_DDR_TOTAL_AP_BASE_ADDR)
#define IB_TELEMETRY_DDR_DIE_0_AP_END_ADDR \
    (IB_TELEMETRY_DDR_TOTAL_AP_BASE_ADDR + IB_TELEMETRY_DDR_PER_DIE_SIZE)

#define IB_TELEMETRY_DDR_DIE_1_AP_BASE_ADDR (IB_TELEMETRY_DDR_DIE_0_AP_END_ADDR)
#define IB_TELEMETRY_DDR_DIE_1_AP_END_ADDR  (IB_TELEMETRY_DDR_TOTAL_AP_END_ADDR)

//Cstate TFA timestamp DDR size is 128KB
#define AP_CSTATE_BUFFER_DDR_PER_DIE_SIZE       (MSCP_ATU_AP_WINDOW_CSTATE_TIMESTAMP_DIE_SIZE)
#define AP_CSTATE_BUFFER_DDR_TOTAL_AP_BASE_ADDR (AP_CSTATE_BUFFER_BASE)
#define AP_CSTATE_BUFFER_DDR_TOTAL_AP_END_ADDR  (AP_CSTATE_BUFFER_BASE + MSCP_ATU_AP_WINDOW_CSTATE_TIMESTAMP_DIE_SIZE)//8K space for both dies
#define AP_CSTATE_BUFFER_DDR_TOTAL_SIZE         (AP_CSTATE_BUFFER_DDR_TOTAL_AP_END_ADDR - AP_CSTATE_BUFFER_DDR_TOTAL_AP_BASE_ADDR)

#define AP_CSTATE_BUFFER_DDR_DIE_AP_BASE_ADDR (AP_CSTATE_BUFFER_DDR_TOTAL_AP_BASE_ADDR)
#define AP_CSTATE_BUFFER_DDR_DIE_AP_END_ADDR   (AP_CSTATE_BUFFER_DDR_TOTAL_AP_END_ADDR)


#define ATU_MODULE_NAME "[ATU_SVC] "
#ifndef NEWLINE
#define NEWLINE "\n"
#endif

#define ATU_LOG_INFO(fmt, ...) printf(ATU_MODULE_NAME fmt NEWLINE, ##__VA_ARGS__)
#define ATU_LOG_WARN(fmt, ...) printf(ATU_MODULE_NAME fmt NEWLINE, ##__VA_ARGS__)
#define ATU_LOG_CRIT(fmt, ...) printf(ATU_MODULE_NAME fmt NEWLINE, ##__VA_ARGS__)

// Macros to decode ATU mapped address into their offsets
#define EVT_TELEMETRY_MANIFEST_GET_DDR_OFFSET(mscp_atu_mapped_addr) \
    ((mscp_atu_mapped_addr) - MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_BASE_ADDR)

/*-------------- Typedefs ----------------*/
/**
 *  @brief ATU service interface type
 *
 *    ATU module will provide a read/write type through the interface to the clients.
 *
 */
typedef enum _atu_api_type
{
    ATU_IO_REQUEST_MAP_SYNC,
    ATU_IO_REQUEST_UNMAP_SYNC,
} atu_api_type_t;

// struct for the atu device object
typedef struct {
    DFWK_DEVICE_HEADER header;
    DFWK_QUEUE default_queue;
} atu_device_t;

// struct for an interface to the atu service
typedef struct  {
    atu_device_t* atu_device;
    DFWK_INTERFACE_HEADER header;
} atu_service_t;

// struct for an request to the atu service
typedef struct {
    DFWK_SYNC_REQUEST_HEADER header;
} atu_service_request_t;
