#
# Copyright (C) Microsoft Corporation. All rights reserved.
#

name: 0.1.0.$(rev:r)

trigger: none

resources:
  pipelines:
  - pipeline: CIPipeline
    source: Kingsgate.MSCP-Official
    branch: main  

variables:
- group: ef-pipeline-config-azurekv    # Centralized PAT Library Group
- name: OfficialBuild
  value : $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
- name: BUILD_ID
  value : $(resources.pipeline.CIPipeline.runID)
- ${{ if variables['OfficialBuild'] }}:
  - name: BuildVersion
    value: $[ variables['Build.BuildNumber'] ]
- ${{ else }}:
  - name: BuildVersion
    value:  $[format('{0}-dev', variables['Build.BuildNumber'])]

# Build stage
stages:
- stage: MSCP_FPGA_Pythia_Tests
  dependsOn: []
  jobs:
  - template: templates/fpga_pythia_test.yaml
    parameters:
      ArtifactName: MSCP
      Pool: 1pfw-kingsgate-big-fpga
      build_id: $(BUILD_ID)

- stage: ACCEL_FPGA_Pythia_Tests
  dependsOn: []
  jobs:
  - template: templates/fpga_pythia_test.yaml
    parameters:
      ArtifactName: ACCEL
      Pool: 1pfw-kingsgate-big-fpga
      build_id: $(BUILD_ID)
      TestPlan: .\tests\functional\test_plan\fpga_nightly_stress_test_plan.args
      ifwi: 'kingsgate.ifwi.ap.baremetal.debug.dat'

# This is to tag the commits that pass weekend stress tests.
- stage: Promote
  dependsOn: [ MSCP_FPGA_Pythia_Tests, ACCEL_FPGA_Pythia_Tests ]
  # Promote only builds triggered on the main branch (ignore PR build triggers), and ignore manual builds triggered on main for publish (prevents re-tagging)
  condition: and(eq(variables['OfficialBuild'], 'true'), ne(variables['Build.Reason'], 'Manual'))
  pool: 
    name: 1pfw-kingsgate-windows
  jobs:
  - template: templates/promote.yaml
    parameters:
      ArtifactName: kingsgate_mscp_$(RunSchedule)_stress
