#
# Copyright (C) Microsoft Corporation. All rights reserved.
#

name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(Rev:r)

trigger: none

variables:
- group: ef-pipeline-config-azurekv    # Centralized PAT Library Group
- name: OfficialBuild
  value : $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

# Build stage
stages:
- stage: Build_Arm_EABI_AARCH_Debug
  dependsOn: []
  jobs:
  - template: templates/build.yaml
    parameters:
      Toolchain: arm-eabi-aarch
      Configuration: Debug
      ArtifactName: Build_Arm_EABI_AARCH_Debug

- stage: SVP_Pythia_Tests_SingleDie
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/svp_pythia_test.yaml
    parameters:
      ArtifactName: SVP_Pythia_Tests_SingleDie
      TestPlan: .\tests\functional\test_plan\svp_single_die_test_plan.args

- stage: SVP_Pythia_Accel_Tests_SingleDie
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/svp_pythia_test.yaml
    parameters:
      ArtifactName: SVP_Pythia_Accel_Tests_SingleDie
      TestPlan: .\tests\functional\test_plan\accel_single_die_test_plan.args
      ifwi: '.\.build\Debug\arm-eabi-aarch\bin\flash\kingsgate.ifwi.ap.baremetal.debug.dat'

- stage: SVP_Pythia_Tests_DualDie
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/svp_pythia_test.yaml
    parameters:
      ArtifactName: SVP_Pythia_Tests_DualDie
      TestPlan: .\tests\functional\test_plan\svp_dual_die_test_plan.args

- stage: ACCEL_FPGA_Pythia_Tests
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/fpga_pythia_test.yaml
    parameters:
      ArtifactName: ACCEL
      Pool: '1pfw-kingsgate-bigfpga-pipelines'
      TestPlan: .\tests\functional\test_plan\accel_single_die_test_plan.args
      ifwi: 'kingsgate.ifwi.ap.baremetal.debug.dat'
      TestVehicleCapability: 'SingleDieFPGA'
  
- stage: MSCP_FPGA_Pythia_Tests
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/fpga_pythia_test.yaml
    parameters:
      ArtifactName: MSCP
      Pool: '1pfw-kingsgate-bigfpga-pipelines'
      TestVehicleCapability: 'SingleDieFPGA'

- stage: MSCP_FPGA_Pythia_Dualdie_Tests
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/fpga_pythia_test.yaml
    parameters:
      ArtifactName: MSCP_DualDie
      TestPlan: .\tests\functional\test_plan\fpga_dual_die_test_plan.args
      #TestVehicleCapability: 'DualDieFPGA'
      #Pool: '1pfw-kingsgate-bigfpga-pipelines'
      TestAgent: 'RDU-120015-DF14'
      Pool: '1pfw-kingsgate-big-fpga'

- stage: MSCP_SOC_Pythia_Singledie_Tests
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/soc_pythia_test.yaml
    parameters:
      ArtifactName: MSCP_SOC_SingleDie
      TestPlan: .\tests\functional\test_plan\soc_single_die_test_plan.args
      TestVehicleCapability: 'SocSingleDie'
      Pool: '1pfw-kingsgate-soc'

# This is to tag the commits that pass nightly tests.
- stage: Promote
  dependsOn: [ Build_Arm_EABI_AARCH_Debug, SVP_Pythia_Tests_SingleDie, SVP_Pythia_Tests_DualDie, MSCP_FPGA_Pythia_Tests, ACCEL_FPGA_Pythia_Tests, MSCP_FPGA_Pythia_Dualdie_Tests]
  # Promote only builds triggered on the main branch (ignore PR build triggers), and ignore manual builds triggered on main for publish (prevents re-tagging)
  condition: and(eq(variables['OfficialBuild'], 'true'), ne(variables['Build.Reason'], 'Manual'))
  pool: 
    name: 1pfw-kingsgate-windows
  jobs:
  - template: templates/promote.yaml
    parameters:
      ArtifactName: kingsgate_mscp_nightly
