#
# Copyright (C) Microsoft Corporation. All rights reserved.
#

name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(Rev:r)

trigger: none

variables:
- group: ef-pipeline-config-azurekv    # Centralized PAT Library Group
- name: OfficialBuild
  value : $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

- name: tdk_repo_name
  value: pythia_tdks
- name: azure_subscription
  value: "Test Firmware Central 2-Woodinville"
- name: nuget_service_connections
  value: ""
- name: keyvault_name
  value: "chie-1pfw"
- name: tdk_repo_name
  value: "$(System.DefaultWorkingDirectory)/"


# Build stage
stages:
- stage: Build_Arm_EABI_AARCH_Debug
  dependsOn: []
  jobs:
  - template: templates/build.yaml
    parameters:
      Toolchain: arm-eabi-aarch
      Configuration: Debug
      ArtifactName: Build_Arm_EABI_AARCH_Debug

- stage: SVP_Pythia_Tests_SingleDie_0
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/svp_pythia_test.yaml@self
    parameters:
      ArtifactName: SVP_Pythia_Tests_SingleDie_0
      TestPlan: .\tests\functional\test_plan\svp_single_die_0_test_plan.args

- stage: SVP_Pythia_Tests_SingleDie_1
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/svp_pythia_test.yaml@self
    parameters:
      ArtifactName: SVP_Pythia_Tests_SingleDie_1
      TestPlan: .\tests\functional\test_plan\svp_single_die_1_test_plan.args

- stage: SVP_Pythia_Accel_Tests_SingleDie
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/svp_pythia_test.yaml
    parameters:
      ArtifactName: SVP_Pythia_Accel_Tests_SingleDie
      TestPlan: .\tests\functional\test_plan\accel_single_die_test_plan.args
      ifwi: '.\.build\Debug\arm-eabi-aarch\bin\flash\kingsgate.ifwi.ap.baremetal.debug.dat'

- stage: SVP_Pythia_Tests_DualDie_0
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/svp_pythia_test.yaml@self
    parameters:
      ArtifactName: SVP_Pythia_Tests_DualDie_0
      TestPlan: .\tests\functional\test_plan\svp_dual_die_0_test_plan.args

- stage: SVP_Pythia_Tests_DualDie_1
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/svp_pythia_test.yaml@self
    parameters:
      ArtifactName: SVP_Pythia_Tests_DualDie_1
      TestPlan: .\tests\functional\test_plan\svp_dual_die_1_test_plan.args

- stage: SVP_Pythia_Tests_DualDie_2
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/svp_pythia_test.yaml@self
    parameters:
      ArtifactName: SVP_Pythia_Tests_DualDie_2
      TestPlan: .\tests\functional\test_plan\svp_dual_die_2_test_plan.args

- stage: MSCP_SOC_Pythia_Dualdie_Tests_0
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/soc_pythia_test.yaml
    parameters:
      ArtifactName: MSCP_SOC_DualDie_0
      TestPlan: .\tests\functional\test_plan\soc_dual_die_0_test_plan.args
      TestVehicleCapability: 'SocDualDie'
      Pool: '1pfw-kingsgate-soc'
      tdk_repo_name: ${{ variables.tdk_repo_name }}
      azure_subscription: ${{ variables.azure_subscription }}
      nuget_service_connections: ${{ variables.nuget_service_connections }}
      keyvault_name: ${{ variables.keyvault_name }}

- stage: MSCP_SOC_Pythia_Dualdie_Tests_1
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/soc_pythia_test.yaml
    parameters:
      ArtifactName: MSCP_SOC_DualDie_1
      TestPlan: .\tests\functional\test_plan\soc_dual_die_1_test_plan.args
      TestVehicleCapability: 'SocDualDie'
      Pool: '1pfw-kingsgate-soc'
      tdk_repo_name: ${{ variables.tdk_repo_name }}
      azure_subscription: ${{ variables.azure_subscription }}
      nuget_service_connections: ${{ variables.nuget_service_connections }}
      keyvault_name: ${{ variables.keyvault_name }}


# This is to tag the commits that pass nightly tests.
- stage: Promote
  dependsOn: [ Build_Arm_EABI_AARCH_Debug, SVP_Pythia_Tests_SingleDie_0, SVP_Pythia_Tests_SingleDie_1, SVP_Pythia_Tests_DualDie_0, SVP_Pythia_Tests_DualDie_1, SVP_Pythia_Tests_DualDie_2, MSCP_SOC_Pythia_Dualdie_Tests_0, MSCP_SOC_Pythia_Dualdie_Tests_1]
  # Promote only builds triggered on the main branch (ignore PR build triggers), and ignore manual builds triggered on main for publish (prevents re-tagging)
  condition: and(eq(variables['OfficialBuild'], 'true'), ne(variables['Build.Reason'], 'Manual'))
  pool:
    name: 1pfw-kingsgate-windows
    demands:
    - ImageOverride -equals 1pfw-win2022vNext
  jobs:
  - template: templates/promote.yaml
    parameters:
      ArtifactName: kingsgate_mscp_nightly
