
name: 0.1.2.$(rev:r)

trigger: 
  branches:
    include:
    # Auto trigger pipeline every time there is a PR completion to main, enables promoting (tagging) for official builds
    - main

parameters:
# One Branch Parameter
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

variables:
- group: ef-pipeline-config
# One Branch Variables
- name: system.debug
  value: ${{ parameters.debug }}
- name: WindowsContainerImage
  value: 'onebranch.azurecr.io/windows/ltsc2019/vse2019:latest'
- name: BuildVersion
  value: $[ variables['Build.BuildNumber'] ]

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    cloudvault: # https://aka.ms/obpipelines/cloudvault
      enabled: false
    globalSdl: # https://aka.ms/obpipelines/sdl
      asyncSdl:
        enabled: true
        tsaOptionsFile: .config/tsaoptions.json
      tsa:
        enabled: false # onebranch publish all sdl results to TSA. If TSA is disabled all SDL tools will forced into 'break' build mode.
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      binskim:
        break: true # always break the build on binskim issues in addition to TSA upload
      policheck:
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
      baseline:
        baselineFile: $(Build.SourcesDirectory)\tools\pipelines\baselines\.gdnbaselines
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\tools\pipelines\baselines\.gdnsuppress
      codeql:
        compiled: 
          enabled: true

    stages:
    - stage: Build_x86_Debug
      dependsOn: []
      jobs:
      - template: tools/pipelines/templates/build.yaml@self
        parameters:
          Toolchain: i386-pc-windows-msvc
          Configuration: Debug
          ArtifactName: Build_x86_Debug

    - stage: Build_Arm_EABI_AARCH_Debug
      dependsOn: []
      jobs:
      - template: tools/pipelines/templates/build.yaml@self
        parameters:
          Toolchain: arm-eabi-aarch
          Configuration: Debug
          ArtifactName: Build_Arm_EABI_AARCH_Debug

    - stage: Unit_Test_x86
      dependsOn: Build_x86_Debug
      jobs:
      - template: tools/pipelines/templates/unittest.yaml@self
        parameters:
          Toolchain: i386-pc-windows-msvc
          Configuration: Debug
          BranchCoverage: $(branch_coverage)
          LineCoverage: $(line_coverage)
          ArtifactName: Unit_Test_x86

    - stage: Publish
      dependsOn: [Unit_Test_x86, Build_x86_Debug, Build_Arm_EABI_AARCH_Debug]
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      jobs:
      - template: tools/pipelines/templates/publish.yaml@self
        parameters:
          Toolchain: [i386-pc-windows-msvc, arm-eabi-aarch]
          Version: $(BuildVersion)

    # Promote is to tag the merge commit so that it can be used by tag reference. This stage is configured to tag by BuildNumber after every PR closure.
    - stage: Promote
      dependsOn: [Unit_Test_x86, Build_x86_Debug, Build_Arm_EABI_AARCH_Debug]
      # Promote only builds triggered on the main branch (ignore PR build triggers), and ignore manual builds triggered on main for publish (prevents re-tagging)
      condition: and(eq(variables['OfficialBuild'], 'true'), ne(variables['Build.Reason'], 'Manual'))
      jobs:
      - template: tools/pipelines/templates/promote.yaml@self
