
name: 0.1.0.$(rev:r)

trigger: none

variables:
- group: ef-pipeline-config-azurekv    # New library group for AzureCSI PAT's (1pfw-code-read-autorotated and fpfw-token-autorotated)
- group: ef-pipeline-config            # Old library group for mstsd PATs
- name: OfficialBuild
  value : $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

- ${{ if variables['OfficialBuild'] }}:
  - name: BuildVersion
    value: $[ variables['Build.BuildNumber'] ]
- ${{ else }}:
  - name: BuildVersion
    value:  $[format('{0}', variables['Build.BuildNumber'])]

# Build stage
stages:
- stage: Build_x86_Debug
  dependsOn: []
  jobs:
  - template: templates/build.yaml
    parameters:
      Toolchain: i386-pc-windows-msvc
      Configuration: Debug
      ArtifactName: Build_x86_Debug

- stage: Build_Arm_EABI_AARCH_Debug
  dependsOn: []
  jobs:
  - template: templates/build.yaml
    parameters:
      Toolchain: arm-eabi-aarch
      Configuration: Debug
      ArtifactName: Build_Arm_EABI_AARCH_Debug

- stage: SVP_Pythia_Tests
  dependsOn: [Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/svp_pythia_test.yaml
    parameters:
      ArtifactName: SVP_Pythia_Tests

- stage: Unit_Test_x86
  dependsOn: [Build_x86_Debug, Build_Arm_EABI_AARCH_Debug]
  jobs:
  - template: templates/unittest.yaml
    parameters:
      Toolchain: i386-pc-windows-msvc
      Configuration: Debug
      # Pipeline variables defined within ADO
      BranchCoverage: $(branch_coverage)
      LineCoverage: $(line_coverage)
      ArtifactName: Unit_Test_x86

- stage: Publish
  dependsOn: [Unit_Test_x86, Build_x86_Debug, Build_Arm_EABI_AARCH_Debug, SVP_Pythia_Tests]
  condition: eq(variables['OfficialBuild'], 'true')
  pool: 
    name: 1pfw-kingsgate-windows
  jobs:
  - template: templates/publish.yaml
    parameters:
      Toolchain: [arm-eabi-aarch]
      Version: $(BuildVersion)
