
name: 0.1.0.$(rev:r)

trigger: none

resources:
  pipelines:
  - pipeline: CIPipeline
    source: kingsgate.mscp.ci
    branch: main  

variables:
- group: ef-pipeline-config
- name: OfficialBuild
  value : $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
- name: BUILD_ID
  value : $(resources.pipeline.CIPipeline.runID)
- ${{ if variables['OfficialBuild'] }}:
  - name: BuildVersion
    value: $[ variables['Build.BuildNumber'] ]
- ${{ else }}:
  - name: BuildVersion
    value:  $[format('{0}-dev', variables['Build.BuildNumber'])]

stages:
- stage: SVP_Pythia_Nightly_Stress_Tests
  jobs:
  - template: templates/svp_pythia_test.yaml
    parameters:
      ArtifactName: SVP_Pythia_Nightly_Stress_Tests
      build_id: $(BUILD_ID)
      TestPlan: .\tests\functional\pythia\test_plan\svp_nightly_stress_test_plan.args
