
name: 0.1.0.$(rev:r)

trigger: none

resources:
  pipelines:
  - pipeline: CIPipeline
    source: kingsgate.mscp.ci
    branch: main  

variables:
- group: ef-pipeline-config-azurekv    # Centralized PAT Library Group
- name: OfficialBuild
  value : $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
- name: BUILD_ID
  value : $(resources.pipeline.CIPipeline.runID)
- ${{ if variables['OfficialBuild'] }}:
  - name: BuildVersion
    value: $[ variables['Build.BuildNumber'] ]
- ${{ else }}:
  - name: BuildVersion
    value:  $[format('{0}-dev', variables['Build.BuildNumber'])]

stages:
- stage: SVP_Pythia_Nightly_Stress_Tests
  jobs:
  - template: templates/svp_pythia_test.yaml
    parameters:
      ArtifactName: SVP_Pythia_Nightly_Stress_Tests
      build_id: $(BUILD_ID)
      TestPlan: $(Test_Plan)

# This is to tag the commits that pass nightly tests.
- stage: Promote
  dependsOn: [ SVP_Pythia_Nightly_Stress_Tests ]
  # Promote only builds triggered on the main branch (ignore PR build triggers), and ignore manual builds triggered on main for publish (prevents re-tagging)
  condition: and(eq(variables['OfficialBuild'], 'true'), ne(variables['Build.Reason'], 'Manual'))
  pool: 
    name: 1pfw-kingsgate-windows
  jobs:
  - template: templates/promote.yaml
    parameters:
      ArtifactName: kingsgate_mscp_$(RunSchedule)_stress