//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

/**
 * @file pldm_pdr.h
 * Provides definitions and types for the static pdr repo init.
 */

 #pragma once

 /*-------------- Includes ----------------*/
#include <assert.h>                      // IWYU pragma: keep
#include <stdint.h>
#include <platform_management_component/platform_description_record.h>

 /*-- Symbolic Constant Macros (defines) --*/
/*-------------- Typedefs ----------------*/

typedef struct
{
    union
    {
        struct
        {
            uint8_t Reserved[5];
            uint8_t Seconds; // 0-59
            uint8_t Minutes; // 0-59
            uint8_t Hours; // 0-23
            uint8_t DayOfTheMonth;
            uint8_t Month; // 1-12
            uint16_t Year;
            uint8_t Format;
        };
        fpfw_pldm_timestamp_104_t as_raw;
    };

} __attribute__((packed)) pldm_pdr_timestamp_t, *p_pldm_pdr_timestamp_t;

 typedef enum _PLDM_BASE_UNIT
 {
     PLDM_BASE_UNIT_NONE = 0,
     PLDM_BASE_UNIT_UNSPECIFIED = 1,
     PLDM_BASE_UNIT_CELCIUS = 2,
     PLDM_BASE_UNIT_VOLTS = 5,
     PLDM_BASE_UNIT_AMPS = 6,
     PLDM_BASE_UNIT_WATTS = 7,
     PLDM_BASE_UNIT_HERTZ = 20
 } PLDM_BASE_UNIT;

typedef enum PLDM_PDR_SENSOR_ID
{
    PLDM_SENSOR_ID_MCP_DUMMY_BASE = 0x0000,
    PLDM_SENSOR_ID_MCP_DUMMY_0,
    PLDM_SENSOR_ID_MCP_DUMMY_1,
    PLDM_SENSOR_ID_MCP_DUMMY_2,
    PLDM_SENSOR_ID_MCP_DUMMY_3,
    PLDM_SENSOR_ID_MCP_DUMMY_4,
    PLDM_SENSOR_ID_MCP_DUMMY_5,
    PLDM_SENSOR_ID_MCP_DUMMY_6,

    PLDM_SENSOR_ID_POWER_TLM_BASE = 0x1000,
    PLDM_SENSOR_ID_POWER_TLM_SOC_TMP_MAX_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_SOC_PWR_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_TMP_MAX_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_TOTAL_PWR_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_VR_TMP_MAX_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_SOC_AVG_FREQ_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_00_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_01_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_02_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_03_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_04_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_05_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_06_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_07_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_08_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_09_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_10_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_TMP_11_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_00_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_01_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_02_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_03_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_04_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_05_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_06_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_07_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_08_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_09_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_10_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_MAX_TMP_11_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_00_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_01_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_02_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_03_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_04_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_05_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_06_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_07_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_08_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_09_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_10_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_DIMM_AVG_PWR_11_NUM_SENS,
    PLDM_SENSOR_ID_POWER_TLM_LAST,

    PLDM_SENSOR_ID_BASE_PWR_CTRL_LOOP_BASE = 0x2000,
    PLDM_SENSOR_ID_MAX
} PLDM_PDR_SENSOR_ID;

typedef enum PLDM_PDR_EFFECTER_ID
{
    PLDM_EFFECTER_ID_MCP_DUMMY_BASE = 0x0000,
    PLDM_EFFECTER_ID_MCP_DUMMY_0,
    PLDM_EFFECTER_ID_MCP_DUMMY_1,
    PLDM_EFFECTER_ID_MAX
} PLDM_PDR_EFFECTER_ID;

/**
 * @brief Retrieves the build timestamp of the PDR repository and formats in pldm_timestamp_t format.
 * @param None
 * @return pldm_pdr_timestamp_t
 */
pldm_pdr_timestamp_t pldm_pdr_get_timestamp(void);
