//
// Copyright (c) Microsoft Corporation.
//

/**
 * @file post_codes.h
 * post code definitions for scp/mcp
 */

#pragma once

/*----------- Nested includes ------------*/

/*-- Symbolic Constant Macros (defines) --*/

/*-------------- Typedefs ----------------*/
//Post codes taken as it is from Pioneer

// SCP range is from 0x40 - 0x5F, and MCP is 0x60 - 0x7F
typedef enum _post_code_t
{
    KINGSGATE_BOOT_POSTCODE_UNUSED = 0,
    POST_CODE_SCP_OK             = 0x40,
    // Add as needed for SCP
    KINGSGATE_BOOT_POSTCODE_START_SCP,
    KINGSGATE_BOOT_POSTCODE_COLD_BOOT_SCP,
    KINGSGATE_BOOT_POSTCODE_WARM_BOOT_SCP,
    KINGSGATE_BOOT_POSTCODE_IRQ_DISABLED_SCP,
    KINGSGATE_BOOT_POSTCODE_E_SIZE_SCP,
    KINGSGATE_BOOT_POSTCODE_E_BOOT_CONFIG_SCP,
    KINGSGATE_BOOT_POSTCODE_E_DATA_SRC_BASE_SCP,
    KINGSGATE_BOOT_POSTCODE_E_IMAGE_SIZE_SCP,
    KINGSGATE_BOOT_POSTCODE_E_ITCRAM_BASE_SCP,
    KINGSGATE_BOOT_POSTCODE_E_ITCRAM_SIZE_SCP,
    KINGSGATE_BOOT_POSTCODE_E_DTCRAM_BASE_SCP,
    KINGSGATE_BOOT_POSTCODE_E_DTCRAM_SIZE_SCP,
    KINGSGATE_BOOT_POSTCODE_E_SEND_HSP_FAILURE_SCP,
	KINGSGATE_BOOT_POSTCODE_E_BOOT_META_SCP,

    POST_CODE_MCP_OK = 0x60,
    // Add as needed for MCP
    KINGSGATE_BOOT_POSTCODE_START_MCP,
    KINGSGATE_BOOT_POSTCODE_COLD_BOOT_MCP,
    KINGSGATE_BOOT_POSTCODE_WARM_BOOT_MCP,
    KINGSGATE_BOOT_POSTCODE_IRQ_DISABLED_MCP,
    KINGSGATE_BOOT_POSTCODE_E_SIZE_MCP,
    KINGSGATE_BOOT_POSTCODE_E_BOOT_CONFIG_MCP,
    KINGSGATE_BOOT_POSTCODE_E_DATA_SRC_BASE_MCP,
    KINGSGATE_BOOT_POSTCODE_E_IMAGE_SIZE_MCP,
    KINGSGATE_BOOT_POSTCODE_E_ITCRAM_BASE_MCP,
    KINGSGATE_BOOT_POSTCODE_E_ITCRAM_SIZE_MCP,
    KINGSGATE_BOOT_POSTCODE_E_DTCRAM_BASE_MCP,
    KINGSGATE_BOOT_POSTCODE_E_DTCRAM_SIZE_MCP,
    KINGSGATE_BOOT_POSTCODE_E_SEND_HSP_FAILURE_MCP,
	KINGSGATE_BOOT_POSTCODE_E_BOOT_META_MCP,
} post_code_t;

/*-- Declarations (Statics and globals) --*/

/*--------- Function Prototypes ----------*/
