//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

/**
 *  @file in_band_telemetry_ddr.h
 *  Header for any in-band telemetry defines, macros, etc.. to reflect how the
 *  DDR is split up for in-band telemetry data.
*/

#pragma once

/*----------- Nested includes ------------*/

#include <assert.h>
#include <atu_api.h>
#include <stdint.h>
#include <utils.h>

/*-- Symbolic Constant Macros (defines) --*/

/**
 * All in-band telemetry data is transferred into DDR (to support reading by the host).
 * All clients share the same range of DDR, and therefore it needs to split it up by
 * client and die.  atu service is responsible for mapping the DDR into the AP window. Atu handles
 * the die split of the total inband telemetry DDR range. Therefore, MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_BASE_ADDR is the
 * same for both both dies, but the window is mapped to die specific DDR ranges.
*/


/**
 * Event Trace uses 16 MB of DDR per die, and starts at the base of each
 * die's DDR range. It's used for both ASIC buffers and HSP buffers.
*/
#ifndef IB_TLM_DDR_TEST_OVERRIDE

#define IB_TLM_DDR_ATU_AP_WIN_BASE_ADDR (MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_BASE_ADDR)
#define IB_TLM_DDR_ATU_AP_WIN_END_ADDR (MSCP_ATU_AP_WINDOW_IB_TELEMETRY_DIE_END_ADDR)
#define IB_TLM_DDR_ATU_AP_WIN_END_SIZE (IB_TLM_DDR_ATU_AP_WIN_END_ADDR - IB_TLM_DDR_ATU_AP_WIN_BASE_ADDR)

#else //#ifndef IB_TLM_DDR_TEST_OVERRIDE
#define UT_DDR_SIZE (MB*100)
extern uint8_t ut_ddr_mem[UT_DDR_SIZE];
#define IB_TLM_DDR_ATU_AP_WIN_BASE_ADDR ((uintptr_t)ut_ddr_mem)
#define IB_TLM_DDR_ATU_AP_WIN_END_ADDR ((uintptr_t)(IB_TLM_DDR_ATU_AP_WIN_BASE_ADDR + sizeof(ut_ddr_mem)))
#define IB_TLM_DDR_ATU_AP_WIN_END_SIZE (UT_DDR_SIZE)

#endif //#ifndef IB_TLM_DDR_TEST_OVERRIDE


// total trace is split between HSP and ASIC
#define IB_TLM_DDR_ATU_AP_WIN_TRACE_SIZE (MB * 16)
#define IB_TLM_DDR_ATU_AP_WIN_TRACE_BASE_ADDR (IB_TLM_DDR_ATU_AP_WIN_BASE_ADDR)
#define IB_TLM_DDR_ATU_AP_WIN_TRACE_END_ADDR (IB_TLM_DDR_ATU_AP_WIN_TRACE_BASE_ADDR + IB_TLM_DDR_ATU_AP_WIN_TRACE_SIZE)

#define IB_TLM_DDR_ATU_AP_WIN_TRACE_HSP_SIZE (1 * MB)
#define IB_TLM_DDR_ATU_AP_WIN_TRACE_HSP_BASE_ADDR (IB_TLM_DDR_ATU_AP_WIN_TRACE_BASE_ADDR)
#define IB_TLM_DDR_ATU_AP_WIN_TRACE_HSP_END_ADDR (IB_TLM_DDR_ATU_AP_WIN_TRACE_HSP_BASE_ADDR + IB_TLM_DDR_ATU_AP_WIN_TRACE_HSP_SIZE)

#define IB_TLM_DDR_ATU_AP_WIN_TRACE_ASIC_SIZE (15 * MB)
#define IB_TLM_DDR_ATU_AP_WIN_TRACE_ASIC_BASE_ADDR (IB_TLM_DDR_ATU_AP_WIN_TRACE_HSP_END_ADDR)
#define IB_TLM_DDR_ATU_AP_WIN_TRACE_ASIC_END_ADDR (IB_TLM_DDR_ATU_AP_WIN_TRACE_ASIC_BASE_ADDR + IB_TLM_DDR_ATU_AP_WIN_TRACE_ASIC_SIZE)

static_assert(IB_TLM_DDR_ATU_AP_WIN_TRACE_SIZE == (IB_TLM_DDR_ATU_AP_WIN_TRACE_HSP_SIZE + IB_TLM_DDR_ATU_AP_WIN_TRACE_ASIC_SIZE), "Trace DDR DIE sizes do not add up to total DDR DIE Trace size");

// total manifest space is split between staging areas and combined manifest
#define IB_TLM_DDR_ATU_AP_WIN_MANIFEST_SIZE (MB * 1)
#define IB_TLM_DDR_ATU_AP_WIN_MANIFEST_BASE_ADDR (IB_TLM_DDR_ATU_AP_WIN_TRACE_ASIC_END_ADDR)
#define IB_TLM_DDR_ATU_AP_WIN_MANIFEST_END_ADDR (IB_TLM_DDR_ATU_AP_WIN_MANIFEST_BASE_ADDR + IB_TLM_DDR_ATU_AP_WIN_MANIFEST_SIZE)

#define IB_TLM_DDR_ATU_AP_CORE_STAGING_MANIFEST_SIZE (KB * 128)

#define IB_TLM_DDR_ATU_AP_MSCP_STAGING_MANIFEST_BASE_ADDR (IB_TLM_DDR_ATU_AP_WIN_MANIFEST_BASE_ADDR)
#define IB_TLM_DDR_ATU_AP_MSCP_STAGING_MANIFEST_END_ADDR (IB_TLM_DDR_ATU_AP_MSCP_STAGING_MANIFEST_BASE_ADDR + IB_TLM_DDR_ATU_AP_CORE_STAGING_MANIFEST_SIZE)

#define IB_TLM_DDR_ATU_AP_SDM_CDED_STAGING_MANIFEST_BASE_ADDR (IB_TLM_DDR_ATU_AP_MSCP_STAGING_MANIFEST_END_ADDR)
#define IB_TLM_DDR_ATU_AP_SCM_CDED_STAGING_MANIFEST_END_ADDR (IB_TLM_DDR_ATU_AP_SDM_CDED_STAGING_MANIFEST_BASE_ADDR + IB_TLM_DDR_ATU_AP_CORE_STAGING_MANIFEST_SIZE)

#define IB_TLM_DDR_ATU_AP_KMP_STAGING_MANIFEST_BASE_ADDR (IB_TLM_DDR_ATU_AP_SCM_CDED_STAGING_MANIFEST_END_ADDR)
#define IB_TLM_DDR_ATU_AP_KMP_STAGING_MANIFEST_END_ADDR (IB_TLM_DDR_ATU_AP_KMP_STAGING_MANIFEST_BASE_ADDR + IB_TLM_DDR_ATU_AP_CORE_STAGING_MANIFEST_SIZE)

#define IB_TLM_DDR_ATU_AP_RSVD_STAGING_MANIFEST_BASE_ADDR (IB_TLM_DDR_ATU_AP_KMP_STAGING_MANIFEST_END_ADDR)
#define IB_TLM_DDR_ATU_AP_RSVD_STAGING_MANIFEST_END_ADDR (IB_TLM_DDR_ATU_AP_RSVD_STAGING_MANIFEST_BASE_ADDR + IB_TLM_DDR_ATU_AP_CORE_STAGING_MANIFEST_SIZE)

#define IB_TLM_DDR_ATU_AP_FULL_MANIFEST_SIZE (KB * 512)
#define IB_TLM_DDR_ATU_AP_FULL_MANIFEST_BASE_ADDR (IB_TLM_DDR_ATU_AP_RSVD_STAGING_MANIFEST_END_ADDR)
#define IB_TLM_DDR_ATU_AP_FULL_MANIFEST_END_ADDR (IB_TLM_DDR_ATU_AP_FULL_MANIFEST_BASE_ADDR + IB_TLM_DDR_ATU_AP_FULL_MANIFEST_SIZE)

#define IB_TLM_DDR_PHY_AP_FULL_MANIFEST_BASE_ADDR ((IB_TLM_DDR_ATU_AP_FULL_MANIFEST_BASE_ADDR - IB_TLM_DDR_ATU_AP_WIN_BASE_ADDR) + IB_TELEMETRY_DDR_DIE_0_AP_BASE_ADDR)
#define IB_TLM_DDR_GET_FULL_MANIFEST_OFFSET (IB_TLM_DDR_PHY_AP_FULL_MANIFEST_BASE_ADDR - IB_TELEMETRY_DDR_DIE_0_AP_BASE_ADDR)

static_assert(IB_TLM_DDR_ATU_AP_WIN_MANIFEST_SIZE == ((4 * IB_TLM_DDR_ATU_AP_CORE_STAGING_MANIFEST_SIZE) + IB_TLM_DDR_ATU_AP_FULL_MANIFEST_SIZE), "Manifest staging and full manifest do not add up to total reserved DDR size");

// use remaining DDR space for power telemetry
#define IB_TLM_DDR_ATU_AP_WIN_PWR_TLM_SIZE (IB_TLM_DDR_ATU_AP_WIN_END_ADDR - IB_TLM_DDR_ATU_AP_WIN_MANIFEST_END_ADDR)
#define IB_TLM_DDR_ATU_AP_WIN_PWR_TLM_BASE_ADDR (IB_TLM_DDR_ATU_AP_WIN_MANIFEST_END_ADDR)
#define IB_TLM_DDR_ATU_AP_WIN_PWR_TLM_END_ADDR (IB_TLM_DDR_ATU_AP_WIN_END_ADDR)

/*-------------- Typedefs ----------------*/


/*-- Declarations (Statics and globals) --*/

/*--------- Function Prototypes ----------*/
