//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

/**
 * @file event_trace_providers.h
 * Defines event trace provider ids for providers on every core.
 */

#pragma once

/*----------- Nested includes ------------*/
#include <IFpFwEventTraceProviders.h>

/*-- Symbolic Constant Macros (defines) --*/

/*-------------- Typedefs ----------------*/

// Provider IDs are used for:
//   - Associating events with a Provider
//   - Associating an event level filter with a Provider

typedef enum
{
    EVENT_TRACE_PROVIDER_ID_COMMON_SENSOR_FIFO_SVC = 0x0400,
    EVENT_TRACE_PROVIDER_ID_COMMON_TLM_FUSES_LIB = 0x0401,
    EVENT_TRACE_PROVIDER_ID_COMMON_CRASH_DUMP = 0x0402,
    EVENT_TRACE_PROVIDER_ID_COMMON_STARTUP_SHUTDOWN = 0x0403,
    EVENT_TRACE_PROVIDER_ID_COMMON_HEALTH_MONITOR = 0x0404,
    EVENT_TRACE_PROVIDER_ID_COMMON_WARM_START = 0x0405,
    EVENT_TRACE_PROVIDER_ID_COMMON_EVENT_TRACE_SERVICE = 0x0406,
    EVENT_TRACE_PROVIDER_ID_COMMON_MHU_ICC_TRANSPORT = 0x0407,
    EVENT_TRACE_PROVIDER_ID_COMMON_ACCEL_BOOT_NOTIFY = 0x0408,
    EVENT_TRACE_PROVIDER_ID_COMMON_AP_ADVLOG_PLDM = 0x0409,
    EVENT_TRACE_PROVIDER_ID_COMMON_POWER_PLDM = 0x040A,
    EVENT_TRACE_PROVIDER_ID_COMMON_SEL_MANAGER = 0x040B,
    EVENT_TRACE_PROVIDER_ID_COMMON_DMA_DRIVER = 0x040C,
    EVENT_TRACE_PROVIDER_ID_COMMON_PLDM_DRIVER = 0x040D,
    EVENT_TRACE_PROVIDER_ID_COMMON_AP_CORE = 0x040E,
    EVENT_TRACE_PROVIDER_ID_COMMON_MAX
} EVENT_TRACE_PROVIDER_ID_COMMON;

typedef enum
{
    EVENT_TRACE_PROVIDER_ID_SCP_MAIN = 0x0100,
    EVENT_TRACE_PROVIDER_ID_SCP_FUSE = 0x0101,
    EVENT_TRACE_PROVIDER_ID_SCP_POWER = 0x0109,
    EVENT_TRACE_PROVIDER_ID_SCP_ACCEL_INTR = 0x010A,
    EVENT_TRACE_PROVIDER_ID_SCP_CLI_ACCEL_INT = 0x010B,
    EVENT_TRACE_PROVIDER_ID_SCP_DDR_MANAGER = 0x010C,
    EVENT_TRACE_PROVIDER_ID_SCP_TLM_SERVICE = 0x010D,
    EVENT_TRACE_PROVIDER_ID_SCP_ACCEL_IP = 0x010E,
    EVENT_TRACE_PROVIDER_ID_SCP_PCIE_MANAGER = 0x010F,
    EVENT_TRACE_PROVIDER_ID_SCP_PCIE_DRIVER = 0x0110,
    EVENT_TRACE_PROVIDER_ID_SCP_VAB_DRIVER = 0x0111,

    EVENT_TRACE_PROVIDER_ID_SCP_SENSOR_FIFO_SVC = EVENT_TRACE_PROVIDER_ID_COMMON_SENSOR_FIFO_SVC,
    EVENT_TRACE_PROVIDER_ID_SCP_TLM_FUSES_LIB = EVENT_TRACE_PROVIDER_ID_COMMON_TLM_FUSES_LIB,
    EVENT_TRACE_PROVIDER_ID_SCP_CRASH_DUMP = EVENT_TRACE_PROVIDER_ID_COMMON_CRASH_DUMP,
    EVENT_TRACE_PROVIDER_ID_SCP_HEALTH_MONITOR = EVENT_TRACE_PROVIDER_ID_COMMON_HEALTH_MONITOR,
    EVENT_TRACE_PROVIDER_ID_SCP_MTS_SERVICE = EVENT_TRACE_PROVIDER_FPFW_MTS,
    EVENT_TRACE_PROVIDER_ID_SCP_STARTUP_SHUTDOWN = EVENT_TRACE_PROVIDER_ID_COMMON_STARTUP_SHUTDOWN,
    EVENT_TRACE_PROVIDER_ID_SCP_WARM_START = EVENT_TRACE_PROVIDER_ID_COMMON_WARM_START,
    EVENT_TRACE_PROVIDER_ID_SCP_MHU_ICC_TRANSPORT = EVENT_TRACE_PROVIDER_ID_COMMON_MHU_ICC_TRANSPORT,
    EVENT_TRACE_PROVIDER_ID_SCP_AP_ADVLOG_PLDM = EVENT_TRACE_PROVIDER_ID_COMMON_AP_ADVLOG_PLDM,
    EVENT_TRACE_PROVIDER_ID_SCP_POWER_PLDM = EVENT_TRACE_PROVIDER_ID_COMMON_POWER_PLDM,
    EVENT_TRACE_PROVIDER_ID_SCP_SEL_MANAGER = EVENT_TRACE_PROVIDER_ID_COMMON_SEL_MANAGER,
    EVENT_TRACE_PROVIDER_ID_SCP_ACCEL_BOOT_NOTIFY = EVENT_TRACE_PROVIDER_ID_COMMON_ACCEL_BOOT_NOTIFY,
    EVENT_TRACE_PROVIDER_ID_SCP_DMA_DRIVER = EVENT_TRACE_PROVIDER_ID_COMMON_DMA_DRIVER,
    EVENT_TRACE_PROVIDER_ID_SCP_PLDM_DRIVER = EVENT_TRACE_PROVIDER_ID_COMMON_PLDM_DRIVER,

    EVENT_TRACE_PROVIDER_ID_SCP_MAX
} EVENT_TRACE_PROVIDER_ID_SCP;

typedef enum
{
    EVENT_TRACE_PROVIDER_ID_MCP_MAIN = 0x0200,
    EVENT_TRACE_PROVIDER_ID_MCP_POWER_TLM_SCHEMA = 0x0201,
    EVENT_TRACE_PROVIDER_ID_MCP_INST_TLM_SCHEMA = 0x0202,
    EVENT_TRACE_PROVIDER_ID_MCP_TLM_SERVICE = 0x0203,
    EVENT_TRACE_PROVIDER_ID_MCP_ETR_SERVICE = 0x0204,
    EVENT_TRACE_PROVIDER_ID_MCP_UTC_SYNC_MANAGER = 0x0205,
    EVENT_TRACE_PROVIDER_ID_MCP_SMC_TLM_MCP = 0x0206,

    EVENT_TRACE_PROVIDER_ID_MCP_SENSOR_FIFO_SVC = EVENT_TRACE_PROVIDER_ID_COMMON_SENSOR_FIFO_SVC,
    EVENT_TRACE_PROVIDER_ID_MCP_TLM_FUSES_LIB = EVENT_TRACE_PROVIDER_ID_COMMON_TLM_FUSES_LIB,
    EVENT_TRACE_PROVIDER_ID_MCP_CRASH_DUMP = EVENT_TRACE_PROVIDER_ID_COMMON_CRASH_DUMP,
    EVENT_TRACE_PROVIDER_ID_MCP_HEALTH_MONITOR = EVENT_TRACE_PROVIDER_ID_COMMON_HEALTH_MONITOR,
    EVENT_TRACE_PROVIDER_ID_MCP_MTS_SERVICE = EVENT_TRACE_PROVIDER_FPFW_MTS,
    EVENT_TRACE_PROVIDER_ID_MCP_STARTUP_SHUTDOWN = EVENT_TRACE_PROVIDER_ID_COMMON_STARTUP_SHUTDOWN,
    EVENT_TRACE_PROVIDER_ID_MCP_WARM_START = EVENT_TRACE_PROVIDER_ID_COMMON_WARM_START,
    EVENT_TRACE_PROVIDER_ID_MCP_MHU_ICC_TRANSPORT = EVENT_TRACE_PROVIDER_ID_COMMON_MHU_ICC_TRANSPORT,
    EVENT_TRACE_PROVIDER_ID_MCP_AP_ADVLOG_PLDM = EVENT_TRACE_PROVIDER_ID_COMMON_AP_ADVLOG_PLDM,
    EVENT_TRACE_PROVIDER_ID_MCP_POWER_PLDM = EVENT_TRACE_PROVIDER_ID_COMMON_POWER_PLDM,
    EVENT_TRACE_PROVIDER_ID_MCP_SEL_MANAGER = EVENT_TRACE_PROVIDER_ID_COMMON_SEL_MANAGER,
    EVENT_TRACE_PROVIDER_ID_MCP_ACCEL_BOOT_NOTIFY = EVENT_TRACE_PROVIDER_ID_COMMON_ACCEL_BOOT_NOTIFY,
    EVENT_TRACE_PROVIDER_ID_MCP_DMA_DRIVER = EVENT_TRACE_PROVIDER_ID_COMMON_DMA_DRIVER,
    EVENT_TRACE_PROVIDER_ID_MCP_PLDM_DRIVER = EVENT_TRACE_PROVIDER_ID_COMMON_PLDM_DRIVER,

    EVENT_TRACE_PROVIDER_ID_MCP_MAX
} EVENT_TRACE_PROVIDER_ID_MCP;

/*-- Declarations (Statics and globals) --*/

/*--------- Function Prototypes ----------*/
