//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

/**
 * @file pcie_manager_events.h
 * Event trace helpers for the PCIe manager service.
 */

#pragma once

/*----------- Nested includes ------------*/
#include <event_trace.h>
#include <event_trace_providers.h>

/*-- Symbolic Constant Macros (defines) --*/
#define PCIE_MANAGER_ET_ERROR(type) EventWritePcieManagerErrorNoParam((type))
#define PCIE_MANAGER_ET_ERROR_PARAM(type, param) EventWritePcieManagerErrorParam((param), (type))

// clang-format off

/*-------------- Typedefs ----------------*/
typedef enum
{
    PCIE_MANAGER_ET_ID_ERROR_NOPARAMS,
    PCIE_MANAGER_ET_ID_ERROR_PARAMS,

    PCIE_MANAGER_ET_ID_COUNT
} PCIE_MANAGER_EVENT_ID;

typedef enum
{
    PCIE_MANAGER_ET_TYPE_CONFIG_EVENT_FLAGS_WAIT_FAIL,
    PCIE_MANAGER_ET_TYPE_CONFIG_EVENT_FLAGS_CREATE_FAIL,
    PCIE_MANAGER_ET_TYPE_CONFIG_THREAD_CREATE_FAIL,
    PCIE_MANAGER_ET_TYPE_NULL_SCHEDULE,
    PCIE_MANAGER_ET_TYPE_WORK_QUEUE_CREATE_FAIL,
    PCIE_MANAGER_ET_TYPE_WORKER_THREAD_CREATE_FAIL,
    PCIE_MANAGER_ET_TYPE_LINK_TRAINING_TIMER_CREATE_FAIL,
    PCIE_MANAGER_ET_TYPE_RP_NOT_READY_AFTER_LINK_DOWN,
    PCIE_MANAGER_ET_TYPE_PHYFW_LOAD_EVENT_CREATE_FAIL,
    PCIE_MANAGER_ET_TYPE_PHYFW_LOAD_EVENT_WAIT_FAIL,
    PCIE_MANAGER_ET_TYPE_PHYFW_LOAD_EVENT_SET_FAIL,
    PCIE_MANAGER_ET_TYPE_EINJ_NULL_PAYLOAD,
    PCIE_MANAGER_ET_TYPE_EINJ_INSTANCE_MISMATCH,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_COMPONENT_GROUP,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_SEGMENT,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_BUS,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_TYPE,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_AER_DATA,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_CRC_DATA,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_SEQNUM_DATA,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_DLLP_DATA,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_SYMBOL_DATA,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_FC_DATA,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_RETRY_TLP_DATA,
    PCIE_MANAGER_ET_TYPE_EINJ_INVALID_PHY_INSTANCE,
    PCIE_MANAGER_ET_TYPE_EINJ_RPSS_LOOKUP_FAIL,
    PCIE_MANAGER_ET_TYPE_EINJ_DRIVER_INJECT_FAIL,
    PCIE_MANAGER_ET_TYPE_RPSS_READY_TIMEOUT,
    PCIE_MANAGER_ET_TYPE_SYNC_INVALID_RPSS_INDEX,
    PCIE_MANAGER_ET_TYPE_SYNC_SS_SEND_FAIL,
    PCIE_MANAGER_ET_TYPE_SYNC_INVALID_RP_INDEX,
    PCIE_MANAGER_ET_TYPE_SYNC_RPSS_SEND_FAIL,
    PCIE_MANAGER_ET_TYPE_LINK_TRAINING_FAIL,
    PCIE_MANAGER_ET_TYPE_TIMER_CALLBACK_QUEUE_SEND_FAIL,
    PCIE_MANAGER_ET_TYPE_LINK_TRAINING_TIMER_EXPIRED,

    PCIE_MANAGER_ET_TYPE_COUNT
} PCIE_MANAGER_ET_TYPE_T;

/*-- Declarations (Statics and globals) --*/

FPFW_ET_DEFINE_PROVIDER_EX(EVENT_TRACE_PROVIDER_ID_SCP_PCIE_MANAGER,
                           PcieManagerSvc,
                           FPFW_ET_LEVEL_MASK_INFO | FPFW_ET_LEVEL_MASK_WARNING |
                               FPFW_ET_LEVEL_MASK_ERROR | FPFW_ET_LEVEL_MASK_FATAL |
                               FPFW_ET_LEVEL_MASK_ALWAYS);

FPFW_ET_DEFINE_EVENT(EVENT_TRACE_PROVIDER_ID_SCP_PCIE_MANAGER,
                     PCIE_MANAGER_ET_ID_ERROR_NOPARAMS,
                     PcieManagerErrorNoParam,
                     FPFW_ET_LEVEL_ERROR,
                     FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT8, type))

FPFW_ET_DEFINE_EVENT(EVENT_TRACE_PROVIDER_ID_SCP_PCIE_MANAGER,
                     PCIE_MANAGER_ET_ID_ERROR_PARAMS,
                     PcieManagerErrorParam,
                     FPFW_ET_LEVEL_ERROR,
                     FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, param),
                     FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT8, type))

/*--------- Function Prototypes ----------*/

// clang-format on
