Param(
    # Default silibs location (adjusted to actual repo path under .externs\repo)
    [string]$SilibsDir = (Join-Path $PSScriptRoot '..' '..' '.externs' 'repo' 'silibs'),
    [string]$TargetFile = 'soc_fw_shared/include/memory_map/ddrss_reserved_regions.h',
    [string]$OutDir = (Join-Path $PSScriptRoot '..' '..' 'src' 'libs' 'ddrss' 'ddrss_library' 'inc'),
    [switch]$Force,
    [switch]$VerboseOutput
)

<#!
Generate ddrss_reserved_regions_version.h containing a deterministic 32-bit revision
value derived from the latest silibs git tag touching ddrss_reserved_regions.h.
Mirrors logic of original bash script generate_ddrss_reserved_regions_header.sh.
#>

# Abort on errors
$ErrorActionPreference = 'Stop'

$headerFile = Join-Path $OutDir 'ddrss_reserved_regions_version.h'

if (Test-Path -LiteralPath $headerFile) {
     Remove-Item -LiteralPath $headerFile -Force
}

# Validate silibs repo presence
if (-not (Test-Path -LiteralPath (Join-Path $SilibsDir '.git'))) {
    Write-Host "Warning: silibs repository not found at $SilibsDir. Emitting header with revision 0." -ForegroundColor Yellow
    $tag = 'NO_SILIBS_REPO'
    $revision = 0
    if (-not (Test-Path -LiteralPath $OutDir)) { New-Item -ItemType Directory -Path $OutDir -Force | Out-Null }
    @(
        '#pragma once',
        '',
        '// Copyright (c) Microsoft Corporation. All rights reserved.',
        '',
        '// Auto-generated by generate_ddrss_reserved_regions_version.ps1. Do not edit manually.',
        "#define DDRSS_RESERVED_REGIONS_REVISION $revision",
        '',
        "// Tag basis: $tag (fallback path)"
    ) | Set-Content -LiteralPath $headerFile -Encoding ASCII
    if ($VerboseOutput) { Write-Host "Generated fallback $headerFile with DDRSS_RESERVED_REGIONS_REVISION=$revision" -ForegroundColor Green }
    return
}

Push-Location $SilibsDir
try {
    # Get latest commit touching target file then describe with nearest tag
    $latestCommit = git log -n 1 --pretty=format:'%H' -- $TargetFile
    if (-not $latestCommit) { throw "Failed to get latest commit for $TargetFile" }
    $tag = git describe --tags --abbrev=0 $latestCommit 2>$null
    if (-not $tag) { throw "Failed to determine tag for $TargetFile" }
    
} finally {
    Pop-Location
}

# Compute 32-bit revision via SHA-256 digest truncation.
# We hash the tag string with SHA-256 and take the first 4 bytes (big-endian) as an unsigned 32-bit integer.
$fullHashHex = ([System.BitConverter]::ToString(([System.Security.Cryptography.SHA256]::Create().ComputeHash([System.Text.Encoding]::UTF8.GetBytes($tag)))).Replace('-', ''))
$revision = [Convert]::ToUInt32($fullHashHex.Substring(0,8),16)

# For verbose mode, also show full SHA256 and derived revision.
if ($VerboseOutput) {
    $fullHashHex = ([System.BitConverter]::ToString(([System.Security.Cryptography.SHA256]::Create().ComputeHash([System.Text.Encoding]::UTF8.GetBytes($tag)))).Replace('-', ''))
    Write-Host "Tag: $tag" -ForegroundColor Cyan
    Write-Host "Full SHA256: $fullHashHex" -ForegroundColor Cyan
}

# Emit header
if (-not (Test-Path -LiteralPath $OutDir)) { New-Item -ItemType Directory -Path $OutDir -Force | Out-Null }
@(
    '#pragma once',
    '',
    '// Copyright (c) Microsoft Corporation. All rights reserved.',
    '',
    '// Auto-generated by generate_ddrss_reserved_regions_version.ps1. Do not edit manually.',
    ("#define DDRSS_RESERVED_REGIONS_REVISION 0x{0:X8}" -f $revision),
    '',
    "// Tag basis: $tag"
) | Set-Content -LiteralPath $headerFile -Encoding ASCII

if ($VerboseOutput) {
    Write-Host ("Generated $headerFile with DDRSS_RESERVED_REGIONS_REVISION= 0x{0:X8} ({1}) (tag: $tag)" -f $revision, $revision) -ForegroundColor Green
}
