/**
 * @file status_decoder.c
 *
 */

/*------------- Includes -----------------*/
#include "status_decoder.h"

#include <FpFwAssert.h>     // for FPFW_RUNTIME_ASSERT
#include <FpFwCli.h>        // for FpFwCliPrint, FPFW_CLI_STATUS
#include <FpFwLinkedList.h> // for NULL_LIST_ENTRY
#include <FpFwUtils.h>      // for FPFW_UNUSED, FPFW_ARRAY_SIZE
#include <fpfw_status.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*------------- Typedefs -----------------*/

/*-------- Function Prototypes -----------*/

/*-- Declarations (Statics and globals) --*/

/*------------- Functions ----------------*/
//! @todo Separate this into it's own cli utils menu
const char* get_fpfw_status_code_string(fpfw_status_t errorCode)
{
    switch (errorCode)
    {
    // Generic
    case FPFW_STATUS_SUCCESS:
        return "FPFW_STATUS_SUCCESS";
    case FPFW_STATUS_FAIL:
        return "FPFW_STATUS_FAIL";
    case FPFW_STATUS_NULL_POINTER:
        return "FPFW_STATUS_NULL_POINTER";
    case FPFW_STATUS_INVALID_ARGS:
        return "FPFW_STATUS_INVALID_ARGS";
    case FPFW_STATUS_NOT_IMPLEMENTED:
        return "FPFW_STATUS_NOT_IMPLEMENTED";
    case FPFW_STATUS_OUT_OF_MEMORY:
        return "FPFW_STATUS_OUT_OF_MEMORY";
    case FPFW_STATUS_DISABLED:
        return "FPFW_STATUS_DISABLED";
    case FPFW_STATUS_ACCESS_DENIED:
        return "FPFW_STATUS_ACCESS_DENIED";
    case FPFW_STATUS_PENDING:
        return "FPFW_STATUS_PENDING";
    case FPFW_STATUS_BUSY:
        return "FPFW_STATUS_BUSY";
    case FPFW_STATUS_TIMEOUT:
        return "FPFW_STATUS_TIMEOUT";
    case FPFW_STATUS_EMPTY:
        return "FPFW_STATUS_EMPTY";
    case FPFW_STATUS_INVALID_STATE:
        return "FPFW_STATUS_INVALID_STATE";
    case FPFW_STATUS_ALREADY_INITIALIZED:
        return "FPFW_STATUS_ALREADY_INITIALIZED";
    case FPFW_STATUS_BUFFER_TOO_SMALL:
        return "FPFW_STATUS_BUFFER_TOO_SMALL";
    case FPFW_STATUS_UNKNOWN_TYPE:
        return "FPFW_STATUS_UNKNOWN_TYPE";
    case FPFW_STATUS_NOT_FOUND:
        return "FPFW_STATUS_NOT_FOUND";
    case FPFW_STATUS_UNEXPECTED:
        return "FPFW_STATUS_UNEXPECTED";
    case FPFW_STATUS_READ_FAIL:
        return "FPFW_STATUS_READ_FAIL";
    case FPFW_STATUS_WRITE_FAIL:
        return "FPFW_STATUS_WRITE_FAIL";
    case FPFW_STATUS_PARTIAL_FAIL:
        return "FPFW_STATUS_PARTIAL_FAIL";

    // ICC Transport
    case FPFW_ICC_TRANSPORT_STATUS_SUCCESS:
        return "FPFW_ICC_TRANSPORT_STATUS_SUCCESS";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_NOT_EMPTY:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_NOT_EMPTY";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_NOT_FULL:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_NOT_FULL";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_NO_FLUSH_REQUEST:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_NO_FLUSH_REQUEST";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_FLUSH_NOT_COMPLETE:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_FLUSH_NOT_COMPLETE";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_FLUSH_IS_REQUESTED:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_FLUSH_IS_REQUESTED";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_NO_RECV_DATA:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_NO_RECV_DATA";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_SEND_BUSY:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_SEND_BUSY";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_SEND_NO_CAPACITY:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_SEND_NO_CAPACITY";
    case FPFW_ICC_TRANSPORT_STATUS_FAILED_ERR:
        return "FPFW_ICC_TRANSPORT_STATUS_FAILED_ERR";
    case FPFW_ICC_TRANSPORT_STATUS_NULL_ARG_ERR:
        return "FPFW_ICC_TRANSPORT_STATUS_NULL_ARG_ERR";
    case FPFW_ICC_TRANSPORT_STATUS_INVALID_ARG_ERR:
        return "FPFW_ICC_TRANSPORT_STATUS_INVALID_ARG_ERR";
    case FPFW_ICC_TRANSPORT_STATUS_INVALID_SIZE_ARG_ERR:
        return "FPFW_ICC_TRANSPORT_STATUS_INVALID_SIZE_ARG_ERR";
    case FPFW_ICC_TRANSPORT_STATUS_REQ_SIZE_ERR:
        return "FPFW_ICC_TRANSPORT_STATUS_REQ_SIZE_ERR";
    case FPFW_ICC_TRANSPORT_STATUS_UNSUPPORTED_REQ_ERR:
        return "FPFW_ICC_TRANSPORT_STATUS_UNSUPPORTED_REQ_ERR";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_UNINITIALIZED_ERR:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_UNINITIALIZED_ERR";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_NO_SUPPORT_ERR:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_NO_SUPPORT_ERR";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_INTR_ERR:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_INTR_ERR";
    case FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_CNT_ERR:
        return "FPFW_ICC_TRANSPORT_STATUS_MBX_FIFO_CNT_ERR";

    // ICC Dispatcher
    case FPFW_ICC_DISPATCH_STATUS_SUCCESS:
        return "FPFW_ICC_DISPATCH_STATUS_SUCCESS";
    case FPFW_ICC_DISPATCH_STATUS_NO_REINIT:
        return "FPFW_ICC_DISPATCH_STATUS_NO_REINIT";
    case FPFW_ICC_DISPATCH_STATUS_NULL_ARG_ERR:
        return "FPFW_ICC_DISPATCH_STATUS_NULL_ARG_ERR";
    case FPFW_ICC_DISPATCH_STATUS_INVALID_ARG_ERR:
        return "FPFW_ICC_DISPATCH_STATUS_INVALID_ARG_ERR";
    case FPFW_ICC_DISPATCH_STATUS_INVALID_SIZE_ARG_ERR:
        return "FPFW_ICC_DISPATCH_STATUS_INVALID_SIZE_ARG_ERR";
    case FPFW_ICC_DISPATCH_STATUS_UNINITIALIZED_ERR:
        return "FPFW_ICC_DISPATCH_STATUS_UNINITIALIZED_ERR";
    case FPFW_ICC_DISPATCH_STATUS_CLIENT_INTRF_OPEN_ERR:
        return "FPFW_ICC_DISPATCH_STATUS_CLIENT_INTRF_OPEN_ERR";
    case FPFW_ICC_DISPATCH_STATUS_MATCH_VAL_OUT_OF_RANGE_ERR:
        return "FPFW_ICC_DISPATCH_STATUS_MATCH_VAL_OUT_OF_RANGE_ERR";
    case FPFW_ICC_DISPATCH_STATUS_NO_MATCH_STRATEGY_ERR:
        return "FPFW_ICC_DISPATCH_STATUS_NO_MATCH_STRATEGY_ERR";
    case FPFW_ICC_DISPATCH_STATUS_MATCH_STRATEGY_SIZE_ERR:
        return "FPFW_ICC_DISPATCH_STATUS_MATCH_STRATEGY_SIZE_ERR";
    case FPFW_ICC_DISPATCH_STATUS_MATCH_STRATEGY_CFG_ERR:
        return "FPFW_ICC_DISPATCH_STATUS_MATCH_STRATEGY_CFG_ERR";
    case FPFW_ICC_DISPATCH_STATUS_DUPLICATE_ENTRY_ERR:
        return "FPFW_ICC_DISPATCH_STATUS_DUPLICATE_ENTRY_ERR";

    // ICC Base
    case FPFW_ICC_BASE_STATUS_NO_REINIT:
        return "FPFW_ICC_BASE_STATUS_NO_REINIT";
    case FPFW_ICC_BASE_STATUS_INVALID_SIZE_ARG_ERR:
        return "FPFW_ICC_BASE_STATUS_INVALID_SIZE_ARG_ERR";
    case FPFW_ICC_BASE_STATUS_UNINITIALIZED_ERR:
        return "FPFW_ICC_BASE_STATUS_UNINITIALIZED_ERR";
    case FPFW_ICC_BASE_STATUS_CLIENT_INTRF_OPEN_ERR:
        return "FPFW_ICC_BASE_STATUS_CLIENT_INTRF_OPEN_ERR";
    case FPFW_ICC_BASE_STATUS_DISPATCHER_INIT_ERR:
        return "FPFW_ICC_BASE_STATUS_DISPATCHER_INIT_ERR";
    case FPFW_ICC_BASE_STATUS_SYNC_GET_MAX_SIZE_REQ_ERR:
        return "FPFW_ICC_BASE_STATUS_SYNC_GET_MAX_SIZE_REQ_ERR";
    case FPFW_ICC_BASE_STATUS_ASYNC_SEND_REQ_ERR:
        return "FPFW_ICC_BASE_STATUS_ASYNC_SEND_REQ_ERR";
    case FPFW_ICC_BASE_STATUS_ASYNC_RECV_INVALID_CMD_ERR:
        return "FPFW_ICC_BASE_STATUS_ASYNC_RECV_INVALID_CMD_ERR";
    case FPFW_ICC_BASE_STATUS_DISPATCHER_REGISTER_ERR:
        return "FPFW_ICC_BASE_STATUS_DISPATCHER_REGISTER_ERR";
    case FPFW_ICC_BASE_STATUS_SYNC_RECV_SEQ_MISMATCH_ERR:
        return "FPFW_ICC_BASE_STATUS_SYNC_RECV_SEQ_MISMATCH_ERR";
    case FPFW_ICC_BASE_STATUS_SYNC_SEND_REQ_ERR:
        return "FPFW_ICC_BASE_STATUS_SYNC_SEND_REQ_ERR";
    case FPFW_ICC_BASE_STATUS_SYNC_RECV_REQ_ERR:
        return "FPFW_ICC_BASE_STATUS_SYNC_RECV_REQ_ERR";

        // Event Trace Decoder

    case FPFW_EVENT_TRACE_DECODER_STATUS_DECODED:
        return "FPFW_EVENT_TRACE_DECODER_STATUS_DECODED";
    case FPFW_EVENT_TRACE_DECODER_STATUS_QUEUED:
        return "FPFW_EVENT_TRACE_DECODER_STATUS_QUEUED";
    case FPFW_EVENT_TRACE_DECODER_STATUS_E_DECODE_FAILED:
        return "FPFW_EVENT_TRACE_DECODER_STATUS_E_DECODE_FAILED";

    // Ring Buffer
    case FPFW_RING_BUFFER_FULL:
        return "FPFW_RING_BUFFER_FULL";
    case FPFW_RING_BUFFER_EMPTY:
        return "FPFW_RING_BUFFER_EMPTY";
    case FPFW_RING_BUFFER_ELEMENT_SIZE_MISMATCH:
        return "FPFW_RING_BUFFER_ELEMENT_SIZE_MISMATCH";

    // dw i3c
    case FPFW_I3C_SOFT_RESET_FAIL:
        return "FPFW_I3C_SOFT_RESET_FAIL";
    case FPFW_I3C_NOT_ENABLED:
        return "FPFW_I3C_NOT_ENABLED";
    case FPFW_I3C_BUSY:
        return "FPFW_I3C_BUSY";
    case FPFW_I3C_RX_BUFFER_TOO_SMALL:
        return "FPFW_I3C_RX_BUFFER_TOO_SMALL";
    case FPFW_I3C_SIR_NOT_ALLOWED:
        return "FPFW_I3C_SIR_NOT_ALLOWED";
    case FPFW_I3C_MR_NOT_ALLOWED:
        return "FPFW_I3C_MR_NOT_ALLOWED";
    case FPFW_I3C_UNSUPPORTED_IBI_TYPE:
        return "FPFW_I3C_UNSUPPORTED_IBI_TYPE";
    case FPFW_I3C_ERROR_CRC:
        return "FPFW_I3C_ERROR_CRC";
    case FPFW_I3C_ERROR_PARITY:
        return "FPFW_I3C_ERROR_PARITY";
    case FPFW_I3C_ERROR_FRAME:
        return "FPFW_I3C_ERROR_FRAME";
    case FPFW_I3C_ERROR_OVER_UNDER_FLOW:
        return "FPFW_I3C_ERROR_OVER_UNDER_FLOW";
    case FPFW_I3C_ERROR_EARLY_TERMINATION:
        return "FPFW_I3C_ERROR_EARLY_TERMINATION";
    case FPFW_I3C_ERROR_UNKNOWN_RESPONSE:
        return "FPFW_I3C_ERROR_UNKNOWN_RESPONSE";

    default:
        return "Unknown error code";
    }
}

FPFW_CLI_STATUS print_error_string(int argc, const char** argv)
{
    if (argc != 2)
    {
        FpFwCliPrint("ERROR! Insufficient Args\n");
        FpFwCliPrint("Usage: print_error_string <error_code>\n");
        return CLI_ERROR;
    }

    uint32_t error_code = atoi(argv[1]);
    const char* error_string = get_fpfw_status_code_string(error_code);

    if (error_string != NULL)
    {
        FpFwCliPrint("[%d](dec) [0x%x](hex):    %s\n", error_code, error_code, error_string);
    }
    else
    {
        FpFwCliPrint("Error Code: %d Unknown or Unsupported\n", error_code);
    }

    return CLI_SUCCESS;
}