# DAT Manifest

manifest_version = 2

# Define a custom flavors based on an existing flavors
[dat]

# Build this flavor with
#  datwizard build --flavor "kingsgate.ifwi.svp.debug.custom"
[dat."kingsgate.ifwi.svp.debug.custom"]
extends = "kingsgate.ifwi.svp.debug"
build = true
[dat."kingsgate.ifwi.svp.debug.custom".partition]

mcp                        = { type='file', local='${REPO_APP_BUILD_DIR}/Debug/arm-eabi-aarch/bin/mcp/mcp_boot_loader_embed_fw.bin'}
pe_management_mode         = { type='file', local='${REPO_APP_PATH_echofalls.svp.stmm.build}/build/DEBUG/stmm.pkg'}
pe_security_monitor        = { type='file', local='${REPO_APP_PATH_echofalls.atf.build}/build/echofalls/debug/bl31.bin'}
pe_spm                     = { type='file', local='${REPO_APP_PATH_echofalls.hafnium.build}/build/kingsgate/debug/echofalls_clang/hafnium.bin'}
pe_uefi                    = { type='file', local='${REPO_APP_PATH_echofalls.svp.uefi.build}/build/DEBUG/BL33_AP_UEFI.fd'}
rmm                        = { type='file', local='${REPO_APP_PATH_echofalls.rmm.build}/build/echofalls/debug/rmm.img'}
rom_section                = { type='file', local='${REPO_APP_PATH_kingsgate.sprt.release}/release/sp1/sp1.img'}
scp                        = { type='file', local='${REPO_APP_BUILD_DIR}/Debug/arm-eabi-aarch/bin/scp/scp_boot_loader_embed_fw.bin'}
sprt                       = { type='file', local='${REPO_APP_PATH_kingsgate.sprt.release}/release/sprt/sprt.bin'}
cded_dtcm                  = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/cded/cded_fw_dtcm.bin'}
cded_itcm                  = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/cded/cded_fw_itcm.bin'}
sdm_dtcm                   = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/sdm/sdm_fw_dtcm.bin'}
sdm_itcm                   = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/sdm/sdm_fw_itcm.bin'}
mscp_manifest              = { type='file', local='${REPO_APP_BUILD_DIR}/Debug/arm-eabi-aarch/bin/man/etman.bin'}
accel_manifest             = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/man/etman.bin' }
hsp_telemetry              = { type='file', local='${REPO_APP_PATH_kingsgate.sprt.release}/release/pctool/hsptrace_decoder.json'}
mesh_config                = { type='file', local='${REPO_APP_PATH_kng_mesh_binary_images}/cmn800_mesh_tables.bin' }
ddr_phy                    = { type='file',  local='${REPO_APP_PATH_kng_ddrss_phy_fw_image}/ddrss_phy_train_combined.bin' }
ift_memory_state_clearing  = { type='file', local='${REPO_APP_PATH_IFTVectors}/IFTVectors/ift_memory_state_clearing.bin' }
ift_scan_state_clearing    = { type='file', local='${REPO_APP_PATH_IFTVectors}/IFTVectors/ift_scan_state_clearing.bin' }
rp_exe                     = { type='file', local='${REPO_APP_PATH_echofalls.rp_exe.build}/build/echofalls/debug/rp_exe.bin' }
rp_data                    = { type='file', local='${REPO_APP_PATH_echofalls.rp_data.build}/build/echofalls/debug/rp_data.bin' }

# Build this flavor with
#  datwizard build --flavor "kingsgate.ifwi.soc.debug.custom"
[dat."kingsgate.ifwi.soc.debug.custom"]
extends = "kingsgate.ifwi.soc.debug"
build = true
[dat."kingsgate.ifwi.soc.debug.custom".partition]

mcp                        = { type='file', local='${REPO_APP_BUILD_DIR}/Debug/arm-eabi-aarch/bin/mcp/mcp_boot_loader_embed_fw.bin'}
pe_management_mode         = { type='file', local='${REPO_APP_PATH_echofalls.soc.stmm.build}/build/DEBUG/stmm.pkg'}
pe_security_monitor        = { type='file', local='${REPO_APP_PATH_echofalls.atf.build}/build/echofalls/debug/bl31.bin'}
pe_spm                     = { type='file', local='${REPO_APP_PATH_echofalls.hafnium.build}/build/kingsgate/debug/echofalls_clang/hafnium.bin'}
pe_uefi                    = { type='file', local='${REPO_APP_PATH_echofalls.soc.uefi.build}/build/DEBUG/BL33_AP_UEFI.fd'}
rmm                        = { type='file', local='${REPO_APP_PATH_echofalls.rmm.build}/build/echofalls/debug/rmm.img'}
rom_section                = { type='file', local='${REPO_APP_PATH_kingsgate.sprt.release}/release/sp1/sp1.img'}
scp                        = { type='file', local='${REPO_APP_BUILD_DIR}/Debug/arm-eabi-aarch/bin/scp/scp_boot_loader_embed_fw.bin'}
sprt                       = { type='file', local='${REPO_APP_PATH_kingsgate.sprt.release}/release/sprt/sprt.bin'}
cded_dtcm                  = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/cded/cded_fw_dtcm.bin'}
cded_itcm                  = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/cded/cded_fw_itcm.bin'}
sdm_dtcm                   = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/sdm/sdm_fw_dtcm.bin'}
sdm_itcm                   = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/sdm/sdm_fw_itcm.bin'}
mscp_manifest              = { type='file', local='${REPO_APP_BUILD_DIR}/Debug/arm-eabi-aarch/bin/man/etman.bin'}
accel_manifest             = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/man/etman.bin' }
hsp_telemetry              = { type='file', local='${REPO_APP_PATH_kingsgate.sprt.release}/release/pctool/hsptrace_decoder.json'}
mesh_config                = { type='file', local='${REPO_APP_PATH_kng_mesh_binary_images}/cmn800_mesh_tables.bin' }
ddr_phy                    = { type='file', local='${REPO_APP_PATH_kng_ddrss_phy_fw_image}/ddrss_phy_train_combined.bin' }
rp_exe                     = { type='file', local='${REPO_APP_PATH_echofalls.rp_exe.build}/build/echofalls/debug/rp_exe.bin' }
rp_data                    = { type='file', local='${REPO_APP_PATH_echofalls.rp_data.build}/build/echofalls/debug/rp_data.bin' }
pcie_phy                   = { type='file', local='${REPO_APP_PATH_pcie.phy.bin}/pcie_phy_fw.bin' }
ift_memory_state_clearing  = { type='file', local='${REPO_APP_PATH_IFTVectors}/IFTVectors/ift_memory_state_clearing.bin' }
ift_scan_state_clearing    = { type='file', local='${REPO_APP_PATH_IFTVectors}/IFTVectors/ift_scan_state_clearing.bin' }
fuse_override_die0         = { type='file', local='${REPO_APP_PATH_kng_system_fuse_data}/kng_fpga_override_fuse_values_silicon.bin' }
fuse_override_die1         = { type='file', local='${REPO_APP_PATH_kng_system_fuse_data}/kng_fpga_override_fuse_values_silicon.bin' }

# Build this flavor with
#  datwizard build --flavor "kingsgate.ifwi.ap.baremetal.debug"
[dat."kingsgate.ifwi.ap.baremetal.debug"]
extends = "kingsgate.ifwi.soc.debug"
build = true
[dat."kingsgate.ifwi.ap.baremetal.debug".partition]

mcp                        = { type='file', local='${REPO_APP_BUILD_DIR}/Debug/arm-eabi-aarch/bin/mcp/mcp_boot_loader_embed_fw.bin'}
pe_management_mode         = { type='file', local='${REPO_APP_PATH_echofalls.soc.stmm.build}/build/DEBUG/stmm.pkg'}
pe_security_monitor        = { type='file', local='${REPO_APP_PATH_kingsgate.ap.baremetal}/build/bin/arm-aarch64-none/Debug/ap_test.bin'}
pe_spm                     = { type='file', local='${REPO_APP_PATH_echofalls.hafnium.build}/build/kingsgate/debug/echofalls_clang/hafnium.bin'}
pe_uefi                    = { type='file', local='${REPO_APP_PATH_echofalls.soc.uefi.build}/build/DEBUG/BL33_AP_UEFI.fd'}
rmm                        = { type='file', local='${REPO_APP_PATH_echofalls.rmm.build}/build/echofalls/debug/rmm.img'}
rom_section                = { type='file', local='${REPO_APP_PATH_kingsgate.sprt.release}/release/sp1/sp1.img'}
scp                        = { type='file', local='${REPO_APP_BUILD_DIR}/Debug/arm-eabi-aarch/bin/scp/scp_boot_loader_embed_fw.bin'}
sprt                       = { type='file', local='${REPO_APP_PATH_kingsgate.sprt.release}/release/sprt/sprt.bin'}
cded_dtcm                  = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/cded/cded_fw_dtcm.bin'}
cded_itcm                  = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/cded/cded_fw_itcm.bin'}
sdm_dtcm                   = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/sdm/sdm_fw_dtcm.bin'}
sdm_itcm                   = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/sdm/sdm_fw_itcm.bin'}
mscp_manifest              = { type='file', local='${REPO_APP_BUILD_DIR}/Debug/arm-eabi-aarch/bin/man/etman.bin'}
accel_manifest             = { type='file', local='${REPO_APP_PATH_kingsgate.sdm.cded}/build/bin/arm-eabi-aarch/Debug/man/etman.bin' }
hsp_telemetry              = { type='file', local='${REPO_APP_PATH_kingsgate.sprt.release}/release/pctool/hsptrace_decoder.json'}
mesh_config                = { type='file', local='${REPO_APP_PATH_kng_mesh_binary_images}/cmn800_mesh_tables.bin' }
ddr_phy                    = { type='file', local='${REPO_APP_PATH_kng_ddrss_phy_fw_image}/ddrss_phy_train_combined.bin' }
rp_exe                     = { type='file', local='${REPO_APP_PATH_echofalls.rp_exe.build}/build/echofalls/debug/rp_exe.bin' }
rp_data                    = { type='file', local='${REPO_APP_PATH_echofalls.rp_data.build}/build/echofalls/debug/rp_data.bin' }
pcie_phy                   = { type='file', local='${REPO_APP_PATH_pcie.phy.bin}/pcie_phy_fw.bin' }
ift_memory_state_clearing  = { type='file', local='${REPO_APP_PATH_IFTVectors}/IFTVectors/ift_memory_state_clearing.bin' }
ift_scan_state_clearing    = { type='file', local='${REPO_APP_PATH_IFTVectors}/IFTVectors/ift_scan_state_clearing.bin' }
fuse_override_die0         = { type='file', local='${REPO_APP_PATH_kng_system_fuse_data}/kng_fpga_override_fuse_values_silicon.bin' }
fuse_override_die1         = { type='file', local='${REPO_APP_PATH_kng_system_fuse_data}/kng_fpga_override_fuse_values_silicon.bin' }