//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

/**
 * @file mesh_events.h
 * This file defines the event trace events for Mesh
 */

#pragma once

/*----------------------------- Nested includes -----------------------------*/
#include <event_trace.h>
#include <event_trace_providers.h>

/*------------------- Symbolic Constant Macros (defines) --------------------*/

// clang-format off

FPFW_ET_DEFINE_PROVIDER_EX(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,                                                                                                       // ID
    COMMON_MESH,                                                                                                                               // Name
    FPFW_ET_LEVEL_MASK_INFO | FPFW_ET_LEVEL_MASK_WARNING | FPFW_ET_LEVEL_MASK_ERROR | FPFW_ET_LEVEL_MASK_FATAL | FPFW_ET_LEVEL_MASK_ALWAYS     // Logging Level Mask
)

/**
 * Define Event Trace events for the mesh
*/
typedef enum {
    MESH_EVENT_ID_PLATFORM_NOT_SUPPORT = 0,
    MESH_EVENT_ID_NON_SECURE_FAULT_ISR,
    MESH_EVENT_ID_NON_SECURE_ERROR_ISR,
    MESH_EVENT_ID_D2D_ATU_MAP,
    MESH_EVENT_ID_D2D_ATU_UNMAP,
    MESH_EVENT_ID_RAS_ARM_AGENT_SET_BASE,
    MESH_EVENT_ID_RAS_ARM_AGENT_SET_RECORD_COUNTER_THRESHOLDS,
    MESH_EVENT_ID_CONVERT_RAS_RECORD_TO_CPER,
    MESH_EVENT_ID_CLEAR_ERROR_RECORD_STATUS_REGISTER,
    MESH_EVENT_ID_ACPI_FATAL,
    MESH_EVENT_ID_EINJ_INVALID_PAYLOAD,
    MESH_EVENT_ID_VARIABLE_SERVICE_SYNC_GET_VARIABLE_ERROR,
    MESH_EVENT_ID_MISMATCH_NUMA_CONFIG,
    MESH_EVENT_ID_PROCESS_MESH_BINARY_FROM_SPI,
    MESH_EVENT_ID_INVALID_MESH_CONFIG,
    MESH_EVENT_ID_READ_BINARY_TABLE_FROM_RMSS,
    MESH_EVENT_ID_DDRSS_DECODE_ERROR,
    MESH_EVENT_ID_WARM_START,
    MESH_EVENT_ID_COLD_START,

    MESH_EVENT_ID_MAX
} MESH_EVENT_ID;

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_NON_SECURE_FAULT_ISR,
    MeshErrorHandlerNSFaultIsr,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_NON_SECURE_ERROR_ISR,
    MeshErrorHandlerNSErrorIsr,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_CONVERT_RAS_RECORD_TO_CPER,
    MeshErrorHandlerConvertRasRecordToCper,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_RAS_ARM_AGENT_SET_BASE,
    MeshErrorHandlerRasArmAgentSetBase,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_RAS_ARM_AGENT_SET_RECORD_COUNTER_THRESHOLDS,
    MeshErrorHandlerRasSetRecordCntThresholds,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_CLEAR_ERROR_RECORD_STATUS_REGISTER,
    MeshErrorHandlerClearErrorRecordStatusReg,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_ACPI_FATAL,
    MeshErrorHandlerAcpiFatal,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_EINJ_INVALID_PAYLOAD,
    MeshErrorHandlerEinjInvalidPayload,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_VARIABLE_SERVICE_SYNC_GET_VARIABLE_ERROR,
    MeshVariableServiceSyncGetVariableError,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_MISMATCH_NUMA_CONFIG,
    MeshMismatchNumaConfig,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_PROCESS_MESH_BINARY_FROM_SPI,
    MeshProcessMeshBinaryFromSpi,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_INVALID_MESH_CONFIG,
    MeshInvalidMeshConfig,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_READ_BINARY_TABLE_FROM_RMSS,
    MeshReadBinaryTableFromRmss,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_PLATFORM_NOT_SUPPORT,
    MeshPlatformNotSupport,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_DDRSS_DECODE_ERROR,
    MeshDdrssDecodeError,
    FPFW_ET_LEVEL_ERROR,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_D2D_ATU_MAP,
    MeshD2dAtuMap,
    FPFW_ET_LEVEL_INFO,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_D2D_ATU_UNMAP,
    MeshD2dAtuUnmap,
    FPFW_ET_LEVEL_INFO,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_WARM_START,
    MeshWarmStart,
    FPFW_ET_LEVEL_INFO,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

FPFW_ET_DEFINE_EVENT(
    EVENT_TRACE_PROVIDER_ID_COMMON_MESH,
    MESH_EVENT_ID_COLD_START,
    MeshColdStart,
    FPFW_ET_LEVEL_INFO,
    FPFW_ET_DEFINE_FIELD(FPFW_ET_UINT32, line)
)

/*-------------------------------- Typedefs ---------------------------------*/

/*------------------- Declarations (Statics and globals) --------------------*/

/*--------------------------- Function Prototypes ---------------------------*/

// clang-format on
