//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

/**
 * @file sensor_thresholds.h
 * @brief Common sensor threshold definitions for telemetry and PDR systems
 * 
 * This header-only library provides common sensor threshold macros used across
 * power telemetry services and platform description record (PDR) initialization.
 * 
 * All temperature thresholds are defined in deci-Celsius (1/10 of a degree Celsius).
 * For example: 85°C = 850 deci-Celsius
 */

#ifndef SENSOR_THRESHOLDS_H
#define SENSOR_THRESHOLDS_H

/*-- Symbolic Constant Macros (defines) --*/

//
// Sensor Thresholds + Range Field Support
// - Both the threshold support and the range field support fields need to match
//   for the actual thresholds to be recognized.
//

//
// Sensor Definitions - use defines to simplify PDR creation. Will generate a compile error if
//                      definitions are missing. Must match sensor name when adding sensor.
// - Define all threshold values per sensor. Define as 0 if not used
// - Define the supported thresholds for each sensor
// - Define the supported range fields for each sensor
// - Define all values in ascending order: fatal low < critical low < warning low < warning high < critical high < fatal high.
//   Spec - Section 17.6.2 - https://www.dmtf.org/sites/default/files/standards/documents/DSP0248_1.2.0.pdf
//

// Note: Common sensor threshold definitions (VR_TMP_MAX_*, SOC_TMP_MAX_*, DIMM_TMP_MAX_*, etc.)
// are now provided by sensor_thresholds.h header to ensure consistency across components.

#define SUPPORTED_THRESHOLD_HIGH_WARNING  (1 << 0) // Bit 0
#define SUPPORTED_THRESHOLD_HIGH_CRITICAL (1 << 1) // Bit 1
#define SUPPORTED_THRESHOLD_HIGH_FATAL    (1 << 2) // Bit 2
#define SUPPORTED_THRESHOLD_LOW_WARNING   (1 << 3) // Bit 3
#define SUPPORTED_THRESHOLD_LOW_CRITICAL  (1 << 4) // Bit 4
#define SUPPORTED_THRESHOLD_LOW_FATAL     (1 << 5) // Bit 5
#define SUPPORTED_THRESHOLD_RESERVED      (3 << 6) // Bits 6-7

// Combined threshold support configurations
#define SUPPORTED_THRESHOLDS_CRITICAL_HIGH (SUPPORTED_THRESHOLD_HIGH_CRITICAL)
#define SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH (SUPPORTED_THRESHOLD_HIGH_CRITICAL | SUPPORTED_THRESHOLD_HIGH_FATAL)
#define SUPPORTED_THRESHOLDS_WARNING_HIGH_CRITICAL_HIGH_FATAL_HIGH (SUPPORTED_THRESHOLD_HIGH_WARNING | SUPPORTED_THRESHOLD_HIGH_CRITICAL | SUPPORTED_THRESHOLD_HIGH_FATAL)

//
// NOTE: The version of the spec used does not call out the WARNING level in this field.
//       - WARNING HIGH is supported by default and WARNING LOW is treated as CRITICAL HIGH by the BMC.
//       - BMC: https://azurecsi.visualstudio.com/OpenBMC/_git/intel-pldmd?path=%2Fsrc%2Fnumeric_sensor_handler.cpp&_a=contents&version=GBmicrosoft%2Fmain
//       - Spec - Section 28.4: https://www.dmtf.org/sites/default/files/standards/documents/DSP0248_1.2.0.pdf
//
#define SUPPORTED_RANGE_FIELD_NOMINAL_VALUE_SUPPORTED   (1 << 0) // Bit 0
#define SUPPORTED_RANGE_FIELD_NORMAL_MAX_SUPPORTED      (1 << 1) // Bit 1
#define SUPPORTED_RANGE_FIELD_NORMAL_MIN_SUPPORTED      (1 << 2) // Bit 2
#define SUPPORTED_RANGE_FIELD_WARNING_HIGH_SUPPORTED    (0)      // Supported by default
#define SUPPORTED_RANGE_FIELD_WARNING_LOW_SUPPORTED     (1 << 3) // Treated as CRITICAL HIGH
#define SUPPORTED_RANGE_FIELD_CRITICAL_HIGH_SUPPORTED   (1 << 3) // Bit 3
#define SUPPORTED_RANGE_FIELD_CRITICAL_LOW_SUPPORTED    (1 << 4) // Bit 4
#define SUPPORTED_RANGE_FIELD_FATAL_HIGH_SUPPORTED      (1 << 5) // Bit 5
#define SUPPORTED_RANGE_FIELD_FATAL_LOW_SUPPORTED       (1 << 6) // Bit 6
#define SUPPORTED_RANGE_FIELD_RESERVED                  (1 << 7) // Bit 7

// Combined range field support configurations
#define SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH (SUPPORTED_RANGE_FIELD_CRITICAL_HIGH_SUPPORTED)
#define SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH (SUPPORTED_RANGE_FIELD_CRITICAL_HIGH_SUPPORTED | SUPPORTED_RANGE_FIELD_FATAL_HIGH_SUPPORTED)
#define SUPPORTED_RANGE_FIELDS_WARNING_HIGH_CRITICAL_HIGH_FATAL_HIGH (SUPPORTED_RANGE_FIELD_WARNING_HIGH_SUPPORTED | SUPPORTED_RANGE_FIELD_CRITICAL_HIGH_SUPPORTED | SUPPORTED_RANGE_FIELD_FATAL_HIGH_SUPPORTED)

//
// Sensor Definitions - use defines to simplify PDR creation. Will generate a compile error if
//                      definitions are missing. Must match sensor name when adding sensor.
// - Define all threshold values per sensor. Define as 0 if not used
// - Define the supported thresholds for each sensor
// - Define the supported range fields for each sensor
// - Define all values in ascending order: fatal low < critical low < warning low < warning high < critical high < fatal high.
//   Spec - Section 17.6.2 - https://www.dmtf.org/sites/default/files/standards/documents/DSP0248_1.2.0.pdf
//

#define THRESHOLD_NOT_USED (0U)

//
// Temperature Sensor Thresholds (in deci-Celsius)
//

// VR (Voltage Regulator) Temperature Thresholds
#define VR_TMP_MAX_LOW_FATAL_DC            (THRESHOLD_NOT_USED)
#define VR_TMP_MAX_LOW_CRITICAL_DC         (THRESHOLD_NOT_USED)
#define VR_TMP_MAX_LOW_WARNING_DC          (THRESHOLD_NOT_USED)
#define VR_TMP_MAX_HIGH_WARNING_DC         (1050U)  // 105.0°C
#define VR_TMP_MAX_HIGH_CRITICAL_DC        (1100U)  // 110.0°C
#define VR_TMP_MAX_HIGH_FATAL_DC           (1250U)  // 125.0°C
#define VR_TMP_MAX_SUPPORTED_THRESHOLDS    (SUPPORTED_THRESHOLDS_WARNING_HIGH_CRITICAL_HIGH_FATAL_HIGH)
#define VR_TMP_MAX_SUPPORTED_RANGE_FIELDS  (SUPPORTED_RANGE_FIELDS_WARNING_HIGH_CRITICAL_HIGH_FATAL_HIGH)

// SoC Temperature Thresholds
#define SOC_TMP_MAX_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define SOC_TMP_MAX_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define SOC_TMP_MAX_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define SOC_TMP_MAX_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define SOC_TMP_MAX_HIGH_CRITICAL_DC       (950U)   // 95.0°C
#define SOC_TMP_MAX_HIGH_FATAL_DC          (1150U)  // 115.0°C
#define SOC_TMP_MAX_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define SOC_TMP_MAX_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM (Dual In-line Memory Module) Temperature Thresholds
#define DIMM_TMP_MAX_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_TMP_MAX_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_TMP_MAX_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_TMP_MAX_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_TMP_MAX_HIGH_CRITICAL_DC       (850U)  // 85.0°C
#define DIMM_TMP_MAX_HIGH_FATAL_DC          (950U)  // 95.0°C
#define DIMM_TMP_MAX_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_TMP_MAX_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM Template Thresholds (applied to each unique DIMM)
#define DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC    (850U)  // 85.0°C
#define DIMM_AVG_TMP_XX_HIGH_FATAL_DC       (950U)  // 95.0°C

#define DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC    (850U)  // 85.0°C
#define DIMM_MAX_TMP_XX_HIGH_FATAL_DC       (950U)  // 95.0°C

// DIMM 00 sensor defines
#define DIMM_AVG_TMP_00_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_00_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_00_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_00_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_00_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_00_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_00_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_00_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_00_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_00_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_00_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_00_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_00_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_00_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_00_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_00_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 01 sensor defines
#define DIMM_AVG_TMP_01_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_01_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_01_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_01_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_01_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_01_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_01_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_01_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_01_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_01_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_01_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_01_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_01_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_01_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_01_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_01_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 02 sensor defines
#define DIMM_AVG_TMP_02_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_02_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_02_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_02_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_02_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_02_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_02_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_02_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_02_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_02_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_02_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_02_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_02_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_02_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_02_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_02_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 03 sensor defines
#define DIMM_AVG_TMP_03_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_03_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_03_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_03_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_03_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_03_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_03_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_03_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_03_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_03_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_03_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_03_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_03_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_03_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_03_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_03_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 04 sensor defines
#define DIMM_AVG_TMP_04_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_04_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_04_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_04_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_04_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_04_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_04_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_04_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_04_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_04_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_04_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_04_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_04_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_04_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_04_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_04_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 05 sensor defines
#define DIMM_AVG_TMP_05_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_05_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_05_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_05_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_05_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_05_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_05_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_05_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_05_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_05_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_05_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_05_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_05_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_05_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_05_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_05_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 06 sensor defines
#define DIMM_AVG_TMP_06_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_06_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_06_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_06_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_06_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_06_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_06_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_06_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_06_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_06_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_06_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_06_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_06_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_06_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_06_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_06_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 07 sensor defines
#define DIMM_AVG_TMP_07_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_07_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_07_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_07_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_07_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_07_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_07_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_07_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_07_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_07_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_07_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_07_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_07_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_07_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_07_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_07_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 08 sensor defines
#define DIMM_AVG_TMP_08_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_08_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_08_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_08_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_08_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_08_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_08_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_08_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_08_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_08_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_08_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_08_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_08_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_08_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_08_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_08_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 09 sensor defines
#define DIMM_AVG_TMP_09_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_09_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_09_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_09_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_09_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_09_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_09_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_09_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_09_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_09_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_09_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_09_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_09_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_09_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_09_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_09_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 10 sensor defines
#define DIMM_AVG_TMP_10_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_10_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_10_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_10_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_10_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_10_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_10_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_10_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_10_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_10_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_10_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_10_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_10_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_10_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_10_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_10_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 11 sensor defines
#define DIMM_AVG_TMP_11_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_11_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_11_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_11_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_AVG_TMP_11_HIGH_CRITICAL_DC       (DIMM_AVG_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_AVG_TMP_11_HIGH_FATAL_DC          (DIMM_AVG_TMP_XX_HIGH_FATAL_DC)
#define DIMM_AVG_TMP_11_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_TMP_11_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

#define DIMM_MAX_TMP_11_LOW_FATAL_DC           (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_11_LOW_CRITICAL_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_11_LOW_WARNING_DC         (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_11_HIGH_WARNING_DC        (THRESHOLD_NOT_USED)
#define DIMM_MAX_TMP_11_HIGH_CRITICAL_DC       (DIMM_MAX_TMP_XX_HIGH_CRITICAL_DC)
#define DIMM_MAX_TMP_11_HIGH_FATAL_DC          (DIMM_MAX_TMP_XX_HIGH_FATAL_DC)
#define DIMM_MAX_TMP_11_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_MAX_TMP_11_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// Power Sensor Thresholds (in milli-watts)
#define SOC_PWR_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define SOC_PWR_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define SOC_PWR_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define SOC_PWR_HIGH_WARNING_MW        (400000U)  // 400W
#define SOC_PWR_HIGH_CRITICAL_MW       (425000U)  // 425W
#define SOC_PWR_HIGH_FATAL_MW          (450000U)  // 450W
#define SOC_PWR_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_WARNING_HIGH_CRITICAL_HIGH_FATAL_HIGH)
#define SOC_PWR_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_WARNING_HIGH_CRITICAL_HIGH_FATAL_HIGH)

// DIMM Total Power Thresholds
#define DIMM_TOTAL_PWR_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_TOTAL_PWR_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_TOTAL_PWR_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_TOTAL_PWR_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_TOTAL_PWR_HIGH_CRITICAL_MW       (255000U)  // 255W
#define DIMM_TOTAL_PWR_HIGH_FATAL_MW          (300000U)  // 300W
#define DIMM_TOTAL_PWR_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_TOTAL_PWR_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// Thresholds for the "XX" DIMM power sensors, which are applied to each unique DIMM
#define DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW (21250U)  // 21.25W
#define DIMM_AVG_PWR_XX_HIGH_FATAL_MW    (25000U)  // 25W

// DIMM 00 power sensor defines
#define DIMM_AVG_PWR_00_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_00_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_00_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_00_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_00_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_00_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_00_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_00_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 01 power sensor defines
#define DIMM_AVG_PWR_01_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_01_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_01_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_01_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_01_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_01_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_01_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_01_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 02 power sensor defines
#define DIMM_AVG_PWR_02_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_02_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_02_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_02_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_02_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_02_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_02_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_02_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 03 power sensor defines
#define DIMM_AVG_PWR_03_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_03_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_03_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_03_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_03_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_03_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_03_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_03_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 04 power sensor defines
#define DIMM_AVG_PWR_04_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_04_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_04_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_04_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_04_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_04_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_04_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_04_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 05 power sensor defines
#define DIMM_AVG_PWR_05_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_05_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_05_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_05_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_05_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_05_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_05_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_05_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 06 power sensor defines
#define DIMM_AVG_PWR_06_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_06_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_06_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_06_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_06_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_06_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_06_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_06_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 07 power sensor defines
#define DIMM_AVG_PWR_07_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_07_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_07_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_07_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_07_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_07_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_07_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_07_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 08 power sensor defines
#define DIMM_AVG_PWR_08_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_08_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_08_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_08_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_08_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_08_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_08_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_08_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 09 power sensor defines
#define DIMM_AVG_PWR_09_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_09_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_09_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_09_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_09_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_09_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_09_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_09_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 10 power sensor defines
#define DIMM_AVG_PWR_10_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_10_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_10_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_10_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_10_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_10_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_10_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_10_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)

// DIMM 11 power sensor defines
#define DIMM_AVG_PWR_11_LOW_FATAL_MW           (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_11_LOW_CRITICAL_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_11_LOW_WARNING_MW         (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_11_HIGH_WARNING_MW        (THRESHOLD_NOT_USED)
#define DIMM_AVG_PWR_11_HIGH_CRITICAL_MW       (DIMM_AVG_PWR_XX_HIGH_CRITICAL_MW)
#define DIMM_AVG_PWR_11_HIGH_FATAL_MW          (DIMM_AVG_PWR_XX_HIGH_FATAL_MW)
#define DIMM_AVG_PWR_11_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH_FATAL_HIGH)
#define DIMM_AVG_PWR_11_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH_FATAL_HIGH)
//
// Frequency Sensor Thresholds (in Mega-Hertz)
//

// SoC Average Frequency Thresholds
#define SOC_AVG_FREQ_LOW_FATAL_MHZ          (THRESHOLD_NOT_USED)
#define SOC_AVG_FREQ_LOW_CRITICAL_MHZ       (THRESHOLD_NOT_USED)
#define SOC_AVG_FREQ_LOW_WARNING_MHZ        (THRESHOLD_NOT_USED)
#define SOC_AVG_FREQ_HIGH_WARNING_MHZ       (THRESHOLD_NOT_USED)
#define SOC_AVG_FREQ_HIGH_CRITICAL_MHZ      (3500U)  // 3.5 GHz
#define SOC_AVG_FREQ_HIGH_FATAL_MHZ         (THRESHOLD_NOT_USED)
#define SOC_AVG_FREQ_SUPPORTED_THRESHOLDS   (SUPPORTED_THRESHOLDS_CRITICAL_HIGH)
#define SOC_AVG_FREQ_SUPPORTED_RANGE_FIELDS (SUPPORTED_RANGE_FIELDS_CRITICAL_HIGH)

#endif // SENSOR_THRESHOLDS_H