//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

/**
 *  @file mhu_icc_payloads.h
 *  Header to capture all mhu icc payloads that are mapped via an ATU.
*/

#pragma once

/*----------- Nested includes ------------*/

#include <assert.h>
#include <atu_api.h>
#include <ddrss_reserved_regions.h>
#include <mscp_uefi_shared_ddrss.h>
#include <stdint.h>
#include <utils.h>

/*-- Symbolic Constant Macros (defines) --*/

/**
 * ICC via MHU requires each channel to have a payload for the receiving and sending side of the 
 * channel. The memory used for these payloads depends on the channel used, and requires that 
 * both ends of the channel have access to the memory used. 
 * 
 * This captures the payloads that use DDR as the memory for the payloads, which get mapped into
 * the MSCP via the AP Window. These payloads have a physical address in DDR, but a mapped address
 * into the AP Window on MSCP to enable access from MSCP.
*/

#define OFFSET_FROM_DDR_RESERVATION(addr) ((addr) - ICC_MHU_PAYLOADS_RESERVATION_BASE)
#define ICC_MHU_AP_WINDOW_ADDRESS(addr) (MSCP_ATU_AP_WINDOW_ICC_MHU_PAYLOAD_BASE_ADDR + OFFSET_FROM_DDR_RESERVATION(addr))

/* D0 SCP <-> D0 AP NS  */
#define ICC_MHU_PAYLOADS_D0_SCP_TO_AP_NS_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_SCP_TO_AP_NS_BASE))
#define ICC_MHU_PAYLOADS_D0_SCP_TO_AP_NS_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_SCP_TO_AP_NS_END))

#define ICC_MHU_PAYLOADS_D0_AP_NS_TO_SCP_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_AP_NS_TO_SCP_BASE))
#define ICC_MHU_PAYLOADS_D0_AP_NS_TO_SCP_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_AP_NS_TO_SCP_END))

/* D1 SCP <-> D1 AP NS  */
#define ICC_MHU_PAYLOADS_D1_SCP_TO_AP_NS_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_SCP_TO_AP_NS_BASE))
#define ICC_MHU_PAYLOADS_D1_SCP_TO_AP_NS_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_SCP_TO_AP_NS_END))

#define ICC_MHU_PAYLOADS_D1_AP_NS_TO_SCP_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_AP_NS_TO_SCP_BASE))
#define ICC_MHU_PAYLOADS_D1_AP_NS_TO_SCP_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_AP_NS_TO_SCP_END))

/* D0 SCP <-> D1 SCP  */
#define ICC_MHU_PAYLOADS_D0_SCP_TO_D1_SCP_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_SCP_TO_D1_SCP_BASE))
#define ICC_MHU_PAYLOADS_D0_SCP_TO_D1_SCP_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_SCP_TO_D1_SCP_END))

#define ICC_MHU_PAYLOADS_D1_SCP_TO_D0_SCP_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_SCP_TO_D0_SCP_BASE))
#define ICC_MHU_PAYLOADS_D1_SCP_TO_D0_SCP_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_SCP_TO_D0_SCP_END))

/* D0 MCP <-> D0 AP NS  */
#define ICC_MHU_PAYLOADS_D0_MCP_TO_AP_NS_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_MCP_TO_AP_NS_BASE))
#define ICC_MHU_PAYLOADS_D0_MCP_TO_AP_NS_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_MCP_TO_AP_NS_END))

#define ICC_MHU_PAYLOADS_D0_AP_NS_TO_MCP_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_AP_NS_TO_MCP_BASE))
#define ICC_MHU_PAYLOADS_D0_AP_NS_TO_MCP_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_AP_NS_TO_MCP_END))

/* D1 MCP <-> D1 AP NS  */
#define ICC_MHU_PAYLOADS_D1_MCP_TO_AP_NS_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_MCP_TO_AP_NS_BASE))
#define ICC_MHU_PAYLOADS_D1_MCP_TO_AP_NS_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_MCP_TO_AP_NS_END))

#define ICC_MHU_PAYLOADS_D1_AP_NS_TO_MCP_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_AP_NS_TO_MCP_BASE))
#define ICC_MHU_PAYLOADS_D1_AP_NS_TO_MCP_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_AP_NS_TO_MCP_END))

/* D0 MCP <-> D1 MCP  */
#define ICC_MHU_PAYLOADS_D0_MCP_TO_D1_MCP_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_MCP_TO_D1_MCP_BASE))
#define ICC_MHU_PAYLOADS_D0_MCP_TO_D1_MCP_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D0_MCP_TO_D1_MCP_END))

#define ICC_MHU_PAYLOADS_D1_MCP_TO_D0_MCP_AP_WINDOW_BASE (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_MCP_TO_D0_MCP_BASE))
#define ICC_MHU_PAYLOADS_D1_MCP_TO_D0_MCP_AP_WINDOW_END (ICC_MHU_AP_WINDOW_ADDRESS(ICC_MHU_PAYLOADS_D1_MCP_TO_D0_MCP_END))

/*-------------- Typedefs ----------------*/

/*-- Declarations (Statics and globals) --*/

/*--------- Function Prototypes ----------*/
